Step 1.1 Import Libraries

In [1]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import torch
from sklearn.model_selection import train_test_split, RandomizedSearchCV, GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_curve, auc
from sklearn.metrics import precision_recall_curve, confusion_matrix, log_loss
import joblib
import warnings
warnings.filterwarnings("ignore")  # Ignore warnings for cleaner output

Step 1.2 Import Data

In [2]:
import duckdb, pyarrow
print("DuckDB:", duckdb.__version__)
print("PyArrow:", pyarrow.__version__)

DuckDB: 1.5.1
PyArrow: 23.0.1

In [3]:
!pip install duckdb pyarrow --upgrade

Requirement already satisfied: duckdb in d:\users\s1382037\appdata\local\anaconda3\envs\jupyterenv\lib\site-packages (1.5.1)
Requirement already satisfied: pyarrow in d:\users\s1382037\appdata\local\anaconda3\envs\jupyterenv\lib\site-packages (23.0.1)

In [ ]:
import pandas as pd
from pathlib import Path
from tqdm import tqdm
import gc

# ---------- USER SETTINGS ----------
raw_root = Path(r"D:\Medical_AI\Data\raw_data\2023_to_2025_millisec")
patient_info_path = Path(r"D:\Medical_AI\Data\patient_indexes_max_hour.csv")
keep_test_types = ['flow', 'pressure']
dt_format = '%Y-%m-%d %H:%M:%S.%f'
sample_mode = False
# -----------------------------------

# Load & clean patient info
patient_info = pd.read_csv(patient_info_path, low_memory=False)
patient_info.columns = patient_info.columns.str.strip()
patient_info['patient_number'] = patient_info['patient_number'].astype(str).str.strip()
patient_info['year'] = patient_info['year'].astype(str).str.strip()
patient_info['label'] = patient_info['label'].map({'good': 0, 'bad': 1}).astype('Int64')
patient_info['start_date'] = pd.to_datetime(patient_info['start_date'], errors='coerce')
patient_info['end_date'] = pd.to_datetime(patient_info['end_date'], errors='coerce')
patient_info['machine_year'] = patient_info['patient_number'] + "_" + patient_info['year'].astype(str)

patients = patient_info[['patient_number','year','patient_id','label','start_date','end_date']].drop_duplicates()

# storage
patient_dfs_list = []
patient_meta_list = []

# iterate patients
iter_rows = list(patients.iterrows())
if sample_mode:
    iter_rows = iter_rows[:1]

for idx, row in tqdm(iter_rows, total=len(iter_rows), desc="Patients"):
    machine_number = str(row['patient_number'])
    year = str(row['year'])
    patient_id = int(row['patient_id']) if pd.notna(row['patient_id']) else None
    label = int(row['label']) if pd.notna(row['label']) else None
    start_date = row['start_date']
    end_date = row['end_date']
    folder_prefix = f"{machine_number}_{year}"

    candidate_folders = [p for p in raw_root.rglob("*") if p.is_dir() and p.name.startswith(folder_prefix)]
    if not candidate_folders:
        print(f"Warning: no folder found for {folder_prefix} -> skipping patient_id={patient_id}")
        continue

    # ✅ Match folder to label: label 0 = good, label 1 = bad
    label_suffix = 'good' if label == 0 else 'bad'
    expected_folder_name = f"{folder_prefix}_{label_suffix}"

    chosen_folder = next(
        (f for f in candidate_folders if f.name == expected_folder_name),
        None
    )
    if chosen_folder is None:
        print(f"⚠️  Expected folder '{expected_folder_name}' not found. "
              f"Candidates: {[f.name for f in candidate_folders]} -> skipping patient_id={patient_id}")
        continue

    all_csvs = sorted(chosen_folder.glob("*.csv"))
    if not all_csvs:
        print(f"Warning: no CSV files under folder {chosen_folder} -> skipping patient_id={patient_id}")
        continue

    patient_chunks = []
    machine_year_full = chosen_folder.name

    for csv_file in all_csvs:
        try:
            df_raw = pd.read_csv(csv_file, dtype=str, low_memory=False)
        except Exception as e:
            print(f"  Error reading {csv_file.name}: {e}")
            continue

        df_raw.columns = df_raw.columns.str.strip()
        dt_col = 'Datetime' if 'Datetime' in df_raw.columns else ('datetime' if 'datetime' in df_raw.columns else None)
        if dt_col is None:
            continue

        ts = pd.to_datetime(df_raw[dt_col], format=dt_format, errors='coerce')
        if ts.isna().mean() > 0.2:
            ts = pd.to_datetime(df_raw[dt_col], errors='coerce')
        df_raw['timestamp'] = ts
        df_raw = df_raw.dropna(subset=['timestamp'])
        if df_raw.empty:
            continue

        df_raw = df_raw.rename(columns={c: c.strip().lower() for c in df_raw.columns})
        present = [c for c in df_raw.columns if c in keep_test_types]
        if not present:
            continue

        df_small = df_raw[['timestamp'] + present].copy()
        df_long = df_small.melt(id_vars=['timestamp'], value_vars=present,
                                var_name='test_type', value_name='test_value')
        df_long['test_value'] = pd.to_numeric(df_long['test_value'], errors='coerce')

        df_long['patient_id'] = patient_id
        df_long['label'] = label
        df_long['start_date'] = start_date
        df_long['end_date'] = end_date
        df_long['machine_year_full'] = machine_year_full

        patient_chunks.append(df_long)

        if sum(len(c) for c in patient_chunks) > 5_000_000:
            patient_chunks = [pd.concat(patient_chunks, ignore_index=True)]
            gc.collect()

    if not patient_chunks:
        print(f"  No usable rows for {folder_prefix} (patient_id={patient_id})")
        continue

    df_patient = pd.concat(patient_chunks, ignore_index=True)
    df_patient = df_patient.sort_values('timestamp').reset_index(drop=True)
    final_cols = ['timestamp', 'test_type', 'test_value', 'patient_id', 'label', 'start_date', 'end_date', 'machine_year_full']
    df_final = df_patient[[c for c in final_cols if c in df_patient.columns]].copy()

    patient_dfs_list.append(df_final)
    patient_meta_list.append({
        'patient_id': patient_id,
        'machine_year_full': machine_year_full,
        'n_rows': len(df_final),
        'label': label
    })

    print(f"Built patient_id={patient_id} rows={len(df_final)} label={label} machine_year_full={machine_year_full}")

summary = pd.DataFrame(patient_meta_list).sort_values('patient_id').reset_index(drop=True)
print("\nSummary:")
print(summary)

Patients:   1%|          | 1/87 [00:09<13:54,  9.70s/it]

Built patient_id=1 rows=7148924 machine_year_full=B3A20604054_2023_good

Patients:   2%|▏         | 2/87 [00:16<11:29,  8.11s/it]

Built patient_id=2 rows=5420800 machine_year_full=B3A20605023_2023_good

Patients:   3%|▎         | 3/87 [00:53<29:42, 21.22s/it]

Built patient_id=3 rows=19305604 machine_year_full=B3A20605070_2023_good

Patients:   5%|▍         | 4/87 [01:02<22:26, 16.22s/it]

Built patient_id=4 rows=7042872 machine_year_full=B3A23701088_2025_good

Patients:   6%|▌         | 5/87 [01:15<20:33, 15.04s/it]

Built patient_id=5 rows=9887072 machine_year_full=B3A23C26164_2025_good

Patients:   7%|▋         | 6/87 [01:23<17:07, 12.68s/it]

Built patient_id=6 rows=6387902 machine_year_full=B3A24606034_2025_good

Patients:   8%|▊         | 7/87 [01:36<17:16, 12.95s/it]

Built patient_id=7 rows=9989444 machine_year_full=B3C23619117_2025_good

Patients:   9%|▉         | 8/87 [01:49<17:07, 13.00s/it]

Built patient_id=8 rows=9793832 machine_year_full=B3C23C24308_2025_good

Patients:  10%|█         | 9/87 [02:01<16:13, 12.49s/it]

Built patient_id=9 rows=8372776 machine_year_full=B3C23C27141_2025_good

Patients:  11%|█▏        | 10/87 [02:04<12:25,  9.68s/it]

Built patient_id=10 rows=2858772 machine_year_full=B3C23C27371_2025_good

Patients:  13%|█▎        | 11/87 [02:15<12:56, 10.22s/it]

Built patient_id=11 rows=8599090 machine_year_full=B3C24325207_2025_good

Patients:  14%|█▍        | 12/87 [02:24<12:00,  9.61s/it]

Built patient_id=12 rows=6457898 machine_year_full=B3C24329028_2024_good

Patients:  15%|█▍        | 13/87 [02:31<10:57,  8.89s/it]

Built patient_id=13 rows=5951580 machine_year_full=B3C24406068_2025_good

Patients:  16%|█▌        | 14/87 [02:34<08:48,  7.24s/it]

Built patient_id=14 rows=2955468 machine_year_full=B3C24513126_2025_good

Patients:  17%|█▋        | 15/87 [02:40<08:04,  6.72s/it]

Built patient_id=15 rows=4982618 machine_year_full=B3C24513203_2025_good

Patients:  18%|█▊        | 16/87 [02:45<07:17,  6.16s/it]

Built patient_id=16 rows=4273248 machine_year_full=B3C24513221_2025_good

Patients:  20%|█▉        | 17/87 [02:49<06:39,  5.71s/it]

Built patient_id=17 rows=4239008 machine_year_full=B3C24515251_2025_good

Patients:  21%|██        | 18/87 [02:53<06:00,  5.22s/it]

Built patient_id=18 rows=3588854 machine_year_full=B3C24518077_2025_good

Patients:  22%|██▏       | 19/87 [02:58<05:37,  4.97s/it]

Built patient_id=19 rows=3958090 machine_year_full=B3C24623101_2025_good

Patients:  23%|██▎       | 20/87 [03:09<07:27,  6.68s/it]

Built patient_id=20 rows=7669244 machine_year_full=B3C24623207_2025_good

Patients:  24%|██▍       | 21/87 [03:19<08:39,  7.87s/it]

Built patient_id=21 rows=7680114 machine_year_full=B3C24702027_2025_good

Patients:  25%|██▌       | 22/87 [03:22<06:54,  6.38s/it]

Built patient_id=22 rows=2414536 machine_year_full=B3CBD605550_2025_good

Patients:  26%|██▋       | 23/87 [03:29<06:59,  6.55s/it]

Built patient_id=23 rows=5858670 machine_year_full=B3CBD607039_2025_good

Patients:  28%|██▊       | 24/87 [03:43<09:11,  8.75s/it]

Built patient_id=24 rows=10592820 machine_year_full=B3CBD801013_2025_good

Patients:  29%|██▊       | 25/87 [03:49<08:12,  7.95s/it]

Built patient_id=25 rows=5176926 machine_year_full=B3D21705058_2023_good

Patients:  30%|██▉       | 26/87 [03:53<06:54,  6.79s/it]

Built patient_id=26 rows=3487474 machine_year_full=B3D24403103_2025_good

Patients:  31%|███       | 27/87 [04:09<09:36,  9.61s/it]

Built patient_id=27 rows=11673060 machine_year_full=Y2A17601035_2023_good

Patients:  32%|███▏      | 28/87 [04:14<08:06,  8.24s/it]

Built patient_id=28 rows=4677858 machine_year_full=Y2A18105007_2023_good

Patients:  33%|███▎      | 29/87 [04:22<07:55,  8.19s/it]

Built patient_id=29 rows=6425046 machine_year_full=Y2A18105058_2025_good

Patients:  34%|███▍      | 30/87 [04:34<08:49,  9.29s/it]

Built patient_id=30 rows=8805996 machine_year_full=Y2A18301033_2023_good

Patients:  36%|███▌      | 31/87 [04:50<10:22, 11.12s/it]

Built patient_id=31 rows=11124468 machine_year_full=Y2A18301034_2024_good

Patients:  37%|███▋      | 32/87 [04:58<09:27, 10.32s/it]

Built patient_id=32 rows=6318870 machine_year_full=Y2A18C03159_2023_good

Patients:  38%|███▊      | 33/87 [05:09<09:28, 10.53s/it]

Built patient_id=33 rows=7843686 machine_year_full=Y2A20205196_2025_good

Patients:  39%|███▉      | 34/87 [05:14<07:41,  8.71s/it]

Built patient_id=34 rows=4096920 machine_year_full=Y2A20B03088_2023_good

Patients:  40%|████      | 35/87 [05:24<08:03,  9.29s/it]

Built patient_id=35 rows=8174116 machine_year_full=Y2A21607360_2025_good

Patients:  41%|████▏     | 36/87 [05:29<06:40,  7.85s/it]

Built patient_id=36 rows=4096920 machine_year_full=Y2A21901468_2023_good

Patients:  43%|████▎     | 37/87 [05:35<06:11,  7.43s/it]

Built patient_id=37 rows=5356376 machine_year_full=Y2A21A02145_2025_good

Patients:  44%|████▎     | 38/87 [05:41<05:36,  6.87s/it]

Built patient_id=38 rows=5004166 machine_year_full=Y2A23402121_2025_good

Patients:  45%|████▍     | 39/87 [05:45<04:52,  6.08s/it]

Built patient_id=39 rows=3822602 machine_year_full=Y2A23A01223_2025_good

Patients:  46%|████▌     | 40/87 [05:55<05:43,  7.32s/it]

Built patient_id=40 rows=7963422 machine_year_full=Y2A24306219_2025_good

Patients:  47%|████▋     | 41/87 [06:08<06:47,  8.86s/it]

Built patient_id=41 rows=8355686 machine_year_full=Y2C16702047_2023_good

Patients:  48%|████▊     | 42/87 [06:30<09:37, 12.83s/it]

Built patient_id=42 rows=15886666 machine_year_full=Y2C17902004_2023_good

Patients:  49%|████▉     | 43/87 [06:46<10:04, 13.74s/it]

Built patient_id=43 rows=11990606 machine_year_full=Y2C19408118_2023_bad

Patients:  51%|█████     | 44/87 [07:11<12:26, 17.37s/it]

Built patient_id=44 rows=17336820 machine_year_full=Y2C21604310_2023_good

Patients:  52%|█████▏    | 45/87 [07:25<11:27, 16.38s/it]

Built patient_id=45 rows=10255374 machine_year_full=Y2C21A01536_2025_good

Patients:  53%|█████▎    | 46/87 [07:36<09:58, 14.59s/it]

Built patient_id=46 rows=7657630 machine_year_full=Y2C23103527_2025_good

Patients:  54%|█████▍    | 47/87 [07:45<08:35, 12.89s/it]

Built patient_id=47 rows=6927828 machine_year_full=Y2D21105246_2023_good

Patients:  55%|█████▌    | 48/87 [07:49<06:42, 10.31s/it]

Built patient_id=48 rows=3557928 machine_year_full=Y2D24603180_2025_good

Patients:  56%|█████▋    | 49/87 [07:55<05:38,  8.90s/it]

Built patient_id=49 rows=4541534 machine_year_full=YSA22C14327_2025_good

Patients:  57%|█████▋    | 50/87 [08:09<06:30, 10.56s/it]

Built patient_id=50 rows=10515122 machine_year_full=YSA23120560_2025_good

Patients:  59%|█████▊    | 51/87 [08:26<07:27, 12.42s/it]

Built patient_id=51 rows=11373786 machine_year_full=YSB21607337_2023_good

Patients:  60%|█████▉    | 52/87 [08:31<05:56, 10.19s/it]

Built patient_id=52 rows=4276468 machine_year_full=YSB22707063_2023_good

Patients:  61%|██████    | 53/87 [08:51<07:30, 13.25s/it]

Built patient_id=53 rows=14877416 machine_year_full=YSB23114301_2023_good

Patients:  62%|██████▏   | 54/87 [09:06<07:27, 13.56s/it]

Built patient_id=54 rows=10176930 machine_year_full=YSB23114301_2025_good

Patients:  63%|██████▎   | 55/87 [09:24<08:04, 15.15s/it]

Built patient_id=55 rows=12786192 machine_year_full=YSB23122623_2023_good

Patients:  64%|██████▍   | 56/87 [09:30<06:17, 12.18s/it]

Built patient_id=56 rows=4475402 machine_year_full=YSC22408582_2025_good

Patients:  66%|██████▌   | 57/87 [11:21<20:57, 41.91s/it]

Built patient_id=57 rows=40690940 machine_year_full=YSE23104366_2023_good

Patients:  67%|██████▋   | 58/87 [11:37<16:31, 34.18s/it]

Built patient_id=58 rows=10817320 machine_year_full=B3320402093_2023_bad

Patients:  68%|██████▊   | 59/87 [11:46<12:26, 26.66s/it]

Built patient_id=59 rows=6994232 machine_year_full=B3C21201347_2024_bad

Patients:  69%|██████▉   | 60/87 [11:55<09:32, 21.19s/it]

Built patient_id=60 rows=6748568 machine_year_full=B3C21401167_2023_bad

Patients:  70%|███████   | 61/87 [12:07<08:02, 18.54s/it]

Built patient_id=61 rows=8134388 machine_year_full=B3C23C03251_2024_bad

Patients:  71%|███████▏  | 62/87 [12:21<07:11, 17.25s/it]

Built patient_id=62 rows=10613532 machine_year_full=Y2A18301034_2023_bad

Patients:  72%|███████▏  | 63/87 [12:36<06:35, 16.48s/it]

Built patient_id=63 rows=11148564 machine_year_full=Y2A19102026_2023_bad

Patients:  74%|███████▎  | 64/87 [12:44<05:19, 13.90s/it]

Built patient_id=64 rows=6525468 machine_year_full=Y2A20703184_2023_bad

Patients:  75%|███████▍  | 65/87 [12:49<04:08, 11.30s/it]

Built patient_id=65 rows=4766234 machine_year_full=Y2A20705285_2023_bad

Patients:  76%|███████▌  | 66/87 [12:55<03:26,  9.81s/it]

Built patient_id=66 rows=5356176 machine_year_full=Y2A20B03100_2023_bad

Patients:  77%|███████▋  | 67/87 [13:07<03:27, 10.36s/it]

Built patient_id=67 rows=8682648 machine_year_full=Y2A21104526_2023_bad

Patients:  78%|███████▊  | 68/87 [13:16<03:07,  9.89s/it]

Built patient_id=68 rows=6976454 machine_year_full=Y2A21106018_2023_bad

Patients:  79%|███████▉  | 69/87 [13:25<02:56,  9.81s/it]

Built patient_id=69 rows=7123674 machine_year_full=Y2A21606379_2023_bad

Patients:  80%|████████  | 70/87 [13:37<02:53, 10.20s/it]

Built patient_id=70 rows=8169996 machine_year_full=Y2A21B01199_2023_bad

Patients:  82%|████████▏ | 71/87 [13:58<03:39, 13.73s/it]

Built patient_id=71 rows=14905472 machine_year_full=Y2A22402014_2024_bad

Patients:  83%|████████▎ | 72/87 [14:05<02:54, 11.62s/it]

Built patient_id=72 rows=5436638 machine_year_full=Y2A22602589_2023_bad

Patients:  84%|████████▍ | 73/87 [14:09<02:09,  9.22s/it]

Built patient_id=73 rows=3022608 machine_year_full=Y2A22C03150_2023_bad

Patients:  85%|████████▌ | 74/87 [14:23<02:21, 10.85s/it]

Built patient_id=74 rows=10387804 machine_year_full=Y2C19408075_2024_bad

Patients:  86%|████████▌ | 75/87 [14:46<02:50, 14.25s/it]

Built patient_id=75 rows=11990606 machine_year_full=Y2C19408118_2023_bad

Patients:  87%|████████▋ | 76/87 [15:01<02:41, 14.71s/it]

Built patient_id=76 rows=10735524 machine_year_full=Y2C19408118_2024_bad

Patients:  89%|████████▊ | 77/87 [15:07<01:58, 11.86s/it]

Built patient_id=77 rows=4383706 machine_year_full=Y2C21603388_2023_bad

Patients:  90%|████████▉ | 78/87 [15:14<01:33, 10.37s/it]

Built patient_id=78 rows=5570690 machine_year_full=Y2C21901163_2023_bad

Patients:  91%|█████████ | 79/87 [15:23<01:21, 10.25s/it]

Built patient_id=79 rows=6746592 machine_year_full=Y2D20215150_2023_bad

Patients:  92%|█████████▏| 80/87 [15:29<01:02,  8.93s/it]

Built patient_id=80 rows=4647688 machine_year_full=YSA23117171_2024_bad

Patients:  93%|█████████▎| 81/87 [15:40<00:55,  9.31s/it]

Built patient_id=81 rows=6736070 machine_year_full=YSB21102203_2023_bad

Patients:  94%|█████████▍| 82/87 [15:58<01:00, 12.05s/it]

Built patient_id=82 rows=11215578 machine_year_full=YSB22512445_2023_bad

Patients:  95%|█████████▌| 83/87 [16:02<00:39,  9.79s/it]

Built patient_id=83 rows=3764132 machine_year_full=YSC21603101_2023_bad

Patients:  97%|█████████▋| 84/87 [16:09<00:26,  8.83s/it]

Built patient_id=84 rows=5751414 machine_year_full=YSD21503317_2024_bad

Patients:  98%|█████████▊| 85/87 [16:20<00:18,  9.39s/it]

Built patient_id=85 rows=8302410 machine_year_full=YSD21B03010_2023_bad

Patients:  99%|█████████▉| 86/87 [16:22<00:07,  7.12s/it]

Built patient_id=86 rows=1369896 machine_year_full=YSG22303077_2023_bad

Patients: 100%|██████████| 87/87 [16:25<00:00, 11.33s/it]

Built patient_id=87 rows=3076176 machine_year_full=YSG22303077_2024_bad

Summary:
    patient_id      machine_year_full    n_rows  label
0            1  B3A20604054_2023_good   7148924      0
1            2  B3A20605023_2023_good   5420800      0
2            3  B3A20605070_2023_good  19305604      0
3            4  B3A23701088_2025_good   7042872      0
4            5  B3A23C26164_2025_good   9887072      0
..         ...                    ...       ...    ...
82          83   YSC21603101_2023_bad   3764132      1
83          84   YSD21503317_2024_bad   5751414      1
84          85   YSD21B03010_2023_bad   8302410      1
85          86   YSG22303077_2023_bad   1369896      1
86          87   YSG22303077_2024_bad   3076176      1

[87 rows x 4 columns]

In [10]:
import pandas as pd

summary = pd.DataFrame(patient_meta_list)

pd.set_option('display.max_rows', None)
print(summary)

    patient_id      machine_year_full    n_rows  label
0            1  B3A20604054_2023_good   7148924      0
1            2  B3A20605023_2023_good   5420800      0
2            3  B3A20605070_2023_good  19305604      0
3            4  B3A23701088_2025_good   7042872      0
4            5  B3A23C26164_2025_good   9887072      0
5            6  B3A24606034_2025_good   6387902      0
6            7  B3C23619117_2025_good   9989444      0
7            8  B3C23C24308_2025_good   9793832      0
8            9  B3C23C27141_2025_good   8372776      0
9           10  B3C23C27371_2025_good   2858772      0
10          11  B3C24325207_2025_good   8599090      0
11          12  B3C24329028_2024_good   6457898      0
12          13  B3C24406068_2025_good   5951580      0
13          14  B3C24513126_2025_good   2955468      0
14          15  B3C24513203_2025_good   4982618      0
15          16  B3C24513221_2025_good   4273248      0
16          17  B3C24515251_2025_good   4239008      0
17          18  B3C24518077_2025_good   3588854      0
18          19  B3C24623101_2025_good   3958090      0
19          20  B3C24623207_2025_good   7669244      0
20          21  B3C24702027_2025_good   7680114      0
21          22  B3CBD605550_2025_good   2414536      0
22          23  B3CBD607039_2025_good   5858670      0
23          24  B3CBD801013_2025_good  10592820      0
24          25  B3D21705058_2023_good   5176926      0
25          26  B3D24403103_2025_good   3487474      0
26          27  Y2A17601035_2023_good  11673060      0
27          28  Y2A18105007_2023_good   4677858      0
28          29  Y2A18105058_2025_good   6425046      0
29          30  Y2A18301033_2023_good   8805996      0
30          31  Y2A18301034_2024_good  11124468      0
31          32  Y2A18C03159_2023_good   6318870      0
32          33  Y2A20205196_2025_good   7843686      0
33          34  Y2A20B03088_2023_good   4096920      0
34          35  Y2A21607360_2025_good   8174116      0
35          36  Y2A21901468_2023_good   4096920      0
36          37  Y2A21A02145_2025_good   5356376      0
37          38  Y2A23402121_2025_good   5004166      0
38          39  Y2A23A01223_2025_good   3822602      0
39          40  Y2A24306219_2025_good   7963422      0
40          41  Y2C16702047_2023_good   8355686      0
41          42  Y2C17902004_2023_good  15886666      0
42          43   Y2C19408118_2023_bad  11990606      0
43          44  Y2C21604310_2023_good  17336820      0
44          45  Y2C21A01536_2025_good  10255374      0
45          46  Y2C23103527_2025_good   7657630      0
46          47  Y2D21105246_2023_good   6927828      0
47          48  Y2D24603180_2025_good   3557928      0
48          49  YSA22C14327_2025_good   4541534      0
49          50  YSA23120560_2025_good  10515122      0
50          51  YSB21607337_2023_good  11373786      0
51          52  YSB22707063_2023_good   4276468      0
52          53  YSB23114301_2023_good  14877416      0
53          54  YSB23114301_2025_good  10176930      0
54          55  YSB23122623_2023_good  12786192      0
55          56  YSC22408582_2025_good   4475402      0
56          57  YSE23104366_2023_good  40690940      0
57          58   B3320402093_2023_bad  10817320      1
58          59   B3C21201347_2024_bad   6994232      1
59          60   B3C21401167_2023_bad   6748568      1
60          61   B3C23C03251_2024_bad   8134388      1
61          62   Y2A18301034_2023_bad  10613532      1
62          63   Y2A19102026_2023_bad  11148564      1
63          64   Y2A20703184_2023_bad   6525468      1
64          65   Y2A20705285_2023_bad   4766234      1
65          66   Y2A20B03100_2023_bad   5356176      1
66          67   Y2A21104526_2023_bad   8682648      1
67          68   Y2A21106018_2023_bad   6976454      1
68          69   Y2A21606379_2023_bad   7123674      1
69          70   Y2A21B01199_2023_bad   8169996      1
70          71   Y2A22402014_2024_bad  14905472      1
71          72   Y2A22602589_2023_bad   5436638      1
72          73   Y2A22C03150_2023_bad   3022608      1
73          74   Y2C19408075_2024_bad  10387804      1
74          75   Y2C19408118_2023_bad  11990606      1
75          76   Y2C19408118_2024_bad  10735524      1
76          77   Y2C21603388_2023_bad   4383706      1
77          78   Y2C21901163_2023_bad   5570690      1
78          79   Y2D20215150_2023_bad   6746592      1
79          80   YSA23117171_2024_bad   4647688      1
80          81   YSB21102203_2023_bad   6736070      1
81          82   YSB22512445_2023_bad  11215578      1
82          83   YSC21603101_2023_bad   3764132      1
83          84   YSD21503317_2024_bad   5751414      1
84          85   YSD21B03010_2023_bad   8302410      1
85          86   YSG22303077_2023_bad   1369896      1
86          87   YSG22303077_2024_bad   3076176      1

In [11]:
len(patient_dfs_list)

86

In [12]:
patient_dfs_list[1].head(20)

,timestamp,test_type,test_value,patient_id,label,start_date,end_date,machine_year_full
0,2023-09-25 13:00:34.200,flow,52.60,2,0,2023-09-25 13:00:34,2023-10-31 22:17:08,B3A20605023_2023_good
1,2023-09-25 13:00:34.200,pressure,10.87,2,0,2023-09-25 13:00:34,2023-10-31 22:17:08,B3A20605023_2023_good
2,2023-09-25 13:00:34.400,pressure,11.47,2,0,2023-09-25 13:00:34,2023-10-31 22:17:08,B3A20605023_2023_good
3,2023-09-25 13:00:34.400,flow,127.00,2,0,2023-09-25 13:00:34,2023-10-31 22:17:08,B3A20605023_2023_good
4,2023-09-25 13:00:34.600,flow,126.70,2,0,2023-09-25 13:00:34,2023-10-31 22:17:08,B3A20605023_2023_good
5,2023-09-25 13:00:34.600,pressure,11.39,2,0,2023-09-25 13:00:34,2023-10-31 22:17:08,B3A20605023_2023_good
6,2023-09-25 13:00:34.800,flow,105.20,2,0,2023-09-25 13:00:34,2023-10-31 22:17:08,B3A20605023_2023_good
7,2023-09-25 13:00:34.800,pressure,12.30,2,0,2023-09-25 13:00:34,2023-10-31 22:17:08,B3A20605023_2023_good
8,2023-09-25 13:00:35.000,pressure,5.37,2,0,2023-09-25 13:00:34,2023-10-31 22:17:08,B3A20605023_2023_good
9,2023-09-25 13:00:35.000,flow,54.60,2,0,2023-09-25 13:00:34,2023-10-31 22:17:08,B3A20605023_2023_good
10,2023-09-25 13:00:35.200,pressure,4.52,2,0,2023-09-25 13:00:34,2023-10-31 22:17:08,B3A20605023_2023_good
11,2023-09-25 13:00:35.200,flow,6509.40,2,0,2023-09-25 13:00:34,2023-10-31 22:17:08,B3A20605023_2023_good
12,2023-09-25 13:00:35.400,pressure,5.87,2,0,2023-09-25 13:00:34,2023-10-31 22:17:08,B3A20605023_2023_good
13,2023-09-25 13:00:35.400,flow,-17.80,2,0,2023-09-25 13:00:34,2023-10-31 22:17:08,B3A20605023_2023_good
14,2023-09-25 13:00:35.600,pressure,5.04,2,0,2023-09-25 13:00:34,2023-10-31 22:17:08,B3A20605023_2023_good
15,2023-09-25 13:00:35.600,flow,-8.80,2,0,2023-09-25 13:00:34,2023-10-31 22:17:08,B3A20605023_2023_good
16,2023-09-25 13:00:35.800,pressure,4.69,2,0,2023-09-25 13:00:34,2023-10-31 22:17:08,B3A20605023_2023_good
17,2023-09-25 13:00:35.800,flow,12.50,2,0,2023-09-25 13:00:34,2023-10-31 22:17:08,B3A20605023_2023_good
18,2023-09-25 13:00:36.000,flow,12.90,2,0,2023-09-25 13:00:34,2023-10-31 22:17:08,B3A20605023_2023_good
19,2023-09-25 13:00:36.000,pressure,4.95,2,0,2023-09-25 13:00:34,2023-10-31 22:17:08,B3A20605023_2023_good

# Remove patient #86

In [13]:
df86 = next((df for df in patient_dfs_list if int(df['patient_id'].iloc[0]) == 86), None)

if df86 is not None:
    print(f"Patient 86 — total rows: {len(df86)}")
    print(f"  ts_min  : {df86['timestamp'].min()}")
    print(f"  ts_max  : {df86['timestamp'].max()}")
    print(f"  span    : {(df86['timestamp'].max() - df86['timestamp'].min()).total_seconds() / 86400:.3f} days")
    print(f"  end_date: {df86['end_date'].iloc[0]}")
else:
    print("Patient 86 not found in patient_dfs_list")

Patient 86 not found in patient_dfs_list

In [14]:
patient_dfs_list = [df for df in patient_dfs_list if int(df['patient_id'].iloc[0]) != 86]

# verify
print(f"Total patients after drop: {len(patient_dfs_list)}")
print(f"Patient 86 still exists: {any(int(df['patient_id'].iloc[0]) == 86 for df in patient_dfs_list)}")

Total patients after drop: 86
Patient 86 still exists: False

# drop nan rows

In [16]:
import pandas as pd
import gc
from tqdm import tqdm
from pathlib import Path

OUT_SUMMARY = Path(r"D:\Medical_AI\Data\processed\clean_nan_summary.csv")

results = []

for i, df in tqdm(enumerate(patient_dfs_list, start=1), desc="Cleaning patient_dfs_list"):
    # Basic safety check
    if not isinstance(df, pd.DataFrame):
        results.append({"index": i, "rows_before": 0, "nan_rows": 0, "nan_cells": 0, "rows_after": 0, "note": "not a DataFrame"})
        continue

    rows_before = len(df)
    nan_rows = int(df.isna().any(axis=1).sum())
    nan_cells = int(df.isna().sum().sum())

    if nan_rows > 0:
        # Drop any row with at least one NaN
        df_clean = df.dropna(how='any').reset_index(drop=True)
        rows_after = len(df_clean)
        # Replace the original DataFrame in the list
        patient_dfs_list[i-1] = df_clean
        del df_clean
    else:
        rows_after = rows_before

    # Record results
    results.append({
        "index": i,
        "rows_before": rows_before,
        "nan_rows": nan_rows,
        "nan_cells": nan_cells,
        "rows_after": rows_after
    })

    # Free memory
    del df
    gc.collect()

# Summary DataFrame
summary_df = pd.DataFrame(results)

# Print full summary without truncation
pd.set_option('display.max_rows', None)
print("\nCleaned summary (full):")
print(summary_df.to_string(index=False))

# Save to CSV
try:
    OUT_SUMMARY.parent.mkdir(parents=True, exist_ok=True)
    summary_df.to_csv(OUT_SUMMARY, index=False)
    print(f"\nSaved summary to: {OUT_SUMMARY}")
except Exception as e:
    print("Could not save summary:", e)

Cleaning patient_dfs_list: 86it [03:43,  2.60s/it]

Cleaned summary (full):
 index  rows_before  nan_rows  nan_cells  rows_after
     1      7148924     12474      12474     7136450
     2      5420800   1137770    1137770     4283030
     3     19305604   2918874    2918874    16386730
     4      7042872    683714     683714     6359158
     5      9887072   1268976    1268976     8618096
     6      6387902    895262     895262     5492640
     7      9989444   2602148    2602148     7387296
     8      9793832   2144596    2144596     7649236
     9      8372776   1012418    1012418     7360358
    10      2858772    499272     499272     2359500
    11      8599090   1403716    1403716     7195374
    12      6457898   2012066    2012066     4445832
    13      5951580    371406     371406     5580174
    14      2955468    651492     651492     2303976
    15      4982618   1014542    1014542     3968076
    16      4273248   1175268    1175268     3097980
    17      4239008    706476     706476     3532532
    18      3588854    789302     789302     2799552
    19      3958090    591582     591582     3366508
    20      7669244   1129748    1129748     6539496
    21      7680114   1053574    1053574     6626540
    22      2414536    515056     515056     1899480
    23      5858670   1197492    1197492     4661178
    24     10592820   1057870    1057870     9534950
    25      5176926   1434524    1434524     3742402
    26      3487474    481826     481826     3005648
    27     11673060   2408236    2408236     9264824
    28      4677858     22944      22944     4654914
    29      6425046    596760     596760     5828286
    30      8805996     86156      86156     8719840
    31     11124468   2744880    2744880     8379588
    32      6318870   3441382    3441382     2877488
    33      7843686   1496868    1496868     6346818
    34      4096920      4106       4106     4092814
    35      8174116    769874     769874     7404242
    36      4096920      4106       4106     4092814
    37      5356376   3188884    3188884     2167492
    38      5004166    553666     553666     4450500
    39      3822602    340334     340334     3482268
    40      7963422   1779062    1779062     6184360
    41      8355686   3181994    3181994     5173692
    42     15886666   2072932    2072932    13813734
    43     11990606     46620      46620    11943986
    44     17336820   4305754    4305754    13031066
    45     10255374   2748140    2748140     7507234
    46      7657630   2647122    2647122     5010508
    47      6927828    243960     243960     6683868
    48      3557928   1268530    1268530     2289398
    49      4541534   2562186    2562186     1979348
    50     10515122    905848     905848     9609274
    51     11373786   3066854    3066854     8306932
    52      4276468   1514926    1514926     2761542
    53     14877416   2025984    2025984    12851432
    54     10176930   3120974    3120974     7055956
    55     12786192   4450792    4450792     8335400
    56      4475402    762794     762794     3712608
    57     40690940    117118     117118    40573822
    58     10817320   1608188    1608188     9209132
    59      6994232   1036474    1036474     5957758
    60      6748568    161488     161488     6587080
    61      8134388   4667574    4667574     3466814
    62     10613532   2057344    2057344     8556188
    63     11148564   1108650    1108650    10039914
    64      6525468    465494     465494     6059974
    65      4766234    113320     113320     4652914
    66      5356176   1023388    1023388     4332788
    67      8682648     19008      19008     8663640
    68      6976454   1836502    1836502     5139952
    69      7123674   3033992    3033992     4089682
    70      8169996    252752     252752     7917244
    71     14905472   1747632    1747632    13157840
    72      5436638    849430     849430     4587208
    73      3022608    239062     239062     2783546
    74     10387804   2469822    2469822     7917982
    75     11990606     46620      46620    11943986
    76     10735524    171562     171562    10563962
    77      4383706    378870     378870     4004836
    78      5570690   1243092    1243092     4327598
    79      6746592     70364      70364     6676228
    80      4647688    923354     923354     3724334
    81      6736070     11658      11658     6724412
    82     11215578   2695172    2695172     8520406
    83      3764132     81406      81406     3682726
    84      5751414     28962      28962     5722452
    85      8302410    553150     553150     7749260
    86      3076176    647850     647850     2428326

Saved summary to: D:\Medical_AI\Data\processed\clean_nan_summary.csv

In [17]:
patient_dfs_list[1].head(20)

,timestamp,test_type,test_value,patient_id,label,start_date,end_date,machine_year_full
0,2023-09-25 13:00:34.200,flow,52.60,2,0,2023-09-25 13:00:34,2023-10-31 22:17:08,B3A20605023_2023_good
1,2023-09-25 13:00:34.200,pressure,10.87,2,0,2023-09-25 13:00:34,2023-10-31 22:17:08,B3A20605023_2023_good
2,2023-09-25 13:00:34.400,pressure,11.47,2,0,2023-09-25 13:00:34,2023-10-31 22:17:08,B3A20605023_2023_good
3,2023-09-25 13:00:34.400,flow,127.00,2,0,2023-09-25 13:00:34,2023-10-31 22:17:08,B3A20605023_2023_good
4,2023-09-25 13:00:34.600,flow,126.70,2,0,2023-09-25 13:00:34,2023-10-31 22:17:08,B3A20605023_2023_good
5,2023-09-25 13:00:34.600,pressure,11.39,2,0,2023-09-25 13:00:34,2023-10-31 22:17:08,B3A20605023_2023_good
6,2023-09-25 13:00:34.800,flow,105.20,2,0,2023-09-25 13:00:34,2023-10-31 22:17:08,B3A20605023_2023_good
7,2023-09-25 13:00:34.800,pressure,12.30,2,0,2023-09-25 13:00:34,2023-10-31 22:17:08,B3A20605023_2023_good
8,2023-09-25 13:00:35.000,pressure,5.37,2,0,2023-09-25 13:00:34,2023-10-31 22:17:08,B3A20605023_2023_good
9,2023-09-25 13:00:35.000,flow,54.60,2,0,2023-09-25 13:00:34,2023-10-31 22:17:08,B3A20605023_2023_good
10,2023-09-25 13:00:35.200,pressure,4.52,2,0,2023-09-25 13:00:34,2023-10-31 22:17:08,B3A20605023_2023_good
11,2023-09-25 13:00:35.200,flow,6509.40,2,0,2023-09-25 13:00:34,2023-10-31 22:17:08,B3A20605023_2023_good
12,2023-09-25 13:00:35.400,pressure,5.87,2,0,2023-09-25 13:00:34,2023-10-31 22:17:08,B3A20605023_2023_good
13,2023-09-25 13:00:35.400,flow,-17.80,2,0,2023-09-25 13:00:34,2023-10-31 22:17:08,B3A20605023_2023_good
14,2023-09-25 13:00:35.600,pressure,5.04,2,0,2023-09-25 13:00:34,2023-10-31 22:17:08,B3A20605023_2023_good
15,2023-09-25 13:00:35.600,flow,-8.80,2,0,2023-09-25 13:00:34,2023-10-31 22:17:08,B3A20605023_2023_good
16,2023-09-25 13:00:35.800,pressure,4.69,2,0,2023-09-25 13:00:34,2023-10-31 22:17:08,B3A20605023_2023_good
17,2023-09-25 13:00:35.800,flow,12.50,2,0,2023-09-25 13:00:34,2023-10-31 22:17:08,B3A20605023_2023_good
18,2023-09-25 13:00:36.000,flow,12.90,2,0,2023-09-25 13:00:34,2023-10-31 22:17:08,B3A20605023_2023_good
19,2023-09-25 13:00:36.000,pressure,4.95,2,0,2023-09-25 13:00:34,2023-10-31 22:17:08,B3A20605023_2023_good

# Remove outliers

In [18]:
import pandas as pd
import numpy as np
from tqdm import tqdm

results = []

for i, df in tqdm(enumerate(patient_dfs_list, start=1), desc="Outlier removal per patient"):
    if not isinstance(df, pd.DataFrame) or df.empty:
        results.append({"index": i, "note": "empty or not DataFrame"})
        continue

    df_clean = df.copy()
    stats = {}

    # Process separately for each test_type (pressure, flow)
    for t in ["pressure", "flow"]:
        sub = df_clean[df_clean["test_type"] == t]
        if sub.empty:
            continue

        mean = sub["test_value"].mean()
        std = sub["test_value"].std()

        # Define cutoff range: [mean - 5*std, mean + 5*std]
        lower = mean - 5 * std
        upper = mean + 5 * std

        mask = (df_clean["test_type"] == t) & ~df_clean["test_value"].between(lower, upper)
        outliers = mask.sum()

        # Drop outliers
        df_clean = df_clean.drop(df_clean[mask].index)

        stats[f"{t}_mean"] = mean
        stats[f"{t}_std"] = std
        stats[f"{t}_lower"] = lower
        stats[f"{t}_upper"] = upper
        stats[f"{t}_removed"] = outliers

    # Update the list with the cleaned frame
    patient_dfs_list[i-1] = df_clean.reset_index(drop=True)

    # Record metadata
    results.append({
        "index": i,
        "patient_id": int(df["patient_id"].iloc[0]) if "patient_id" in df.columns else None,
        "rows_before": len(df),
        "rows_after": len(df_clean),
        **stats
    })

# Build summary DataFrame
summary_outliers = pd.DataFrame(results)

pd.set_option("display.max_rows", None)
print("\nOutlier cleaning summary:")
print(summary_outliers.to_string(index=False))

# Save if needed
OUT_OUTLIER_SUMMARY = Path(r"D:\Medical_AI\Data\processed\outlier_summary.csv")
summary_outliers.to_csv(OUT_OUTLIER_SUMMARY, index=False)
print(f"\nSaved outlier summary to: {OUT_OUTLIER_SUMMARY}")

Outlier removal per patient: 86it [03:23,  2.36s/it]

Outlier cleaning summary:
 index  patient_id  rows_before  rows_after  pressure_mean  pressure_std  pressure_lower  pressure_upper  pressure_removed  flow_mean   flow_std   flow_lower  flow_upper  flow_removed
     1           1      7136450     7135722       6.163113      2.043031       -4.052044       16.378271                 0  37.833218  95.540243  -439.867997  515.534434           728
     2           2      4283030     4274567       6.382108      2.580529       -6.520537       19.284753                 3  62.710057 408.058559 -1977.582736 2103.002851          8460
     3           3     16386730    16215531       8.111420      5.968652      -21.731840       37.954679                 8 163.187794 927.452472 -4474.074564 4800.450151        171191
     4           4      6359158     6358944       6.567872      4.170325      -14.283751       27.419495                 0  28.354085  63.131739  -287.304611  344.012781           214
     5           5      8618096     8617832       8.081894      2.908680       -6.461504       22.625293                 0  32.733205  56.939387  -251.963729  317.430140           264
     6           6      5492640     5483309       8.797682      5.588404      -19.144340       36.739705                 0  30.359872  27.618305  -107.731653  168.451396          9331
     7           7      7387296     7387205       7.290679      5.278607      -19.102353       33.683712                 0  41.404751  53.905536  -228.122930  310.932432            91
     8           8      7649236     7649234       7.780446      3.152858       -7.983846       23.544738                 0  63.909255  40.074736  -136.464427  264.282937             2
     9           9      7360358     7359894       7.123788      5.676352      -21.257973       35.505550                 0  39.000999  85.256671  -387.282355  465.284352           464
    10          10      2359500     2359466       6.436274      2.912275       -8.125103       20.997651                 0  34.919292  41.620197  -173.181692  243.020277            34
    11          11      7195374     7195230       5.163432      1.967843       -4.675783       15.002648                66  23.981694  43.939413  -195.715371  243.678758            78
    12          12      4445832     4440352       8.177783      5.130925      -17.476843       33.832408                 0  59.651009 322.874147 -1554.719728 1674.021746          5480
    13          13      5580174     5580112       6.609520      4.665675      -16.718856       29.937896                 0  52.033357  55.964729  -227.790286  331.857000            62
    14          14      2303976     2303969       6.658272      4.533932      -16.011386       29.327930                 0  35.216358  42.624441  -177.905849  248.338566             7
    15          15      3968076     3947740       7.598719      4.070184      -12.752202       27.949640                 0  92.191285 653.927295 -3177.445187 3361.827758         20336
    16          16      3097980     3089023      10.082012      6.979814      -24.817057       44.981082                 0  33.029346  27.039188  -102.166596  168.225289          8957
    17          17      3532532     3531424       6.622864      2.842612       -7.590195       20.835922                 0  26.834962 163.508747  -790.708775  844.378699          1108
    18          18      2799552     2799551       7.624183      4.663691      -15.694273       30.942640                 0  41.941914  36.958294  -142.849556  226.733384             1
    19          19      3366508     3359806       6.511208      4.121285      -14.095216       27.117633                 0  55.093886 409.440028 -1992.106253 2102.294024          6702
    20          20      6539496     6539487       7.633340      2.658213       -5.657727       20.924406                 0  51.460400  38.782722  -142.453208  245.374009             9
    21          21      6626540     6626527       7.278856      3.767115      -11.556720       26.114431                 0  49.614265  42.338308  -162.077277  261.305807            13
    22          22      1899480     1899308       5.702837      3.469580      -11.645064       23.050737                 0  42.409080  96.228484  -438.733338  523.551498           172
    23          23      4661178     4661095       7.147514      3.655919      -11.132080       25.427109                 0  47.817460  26.613510   -85.250090  180.885010            83
    24          24      9534950     9534710       7.766696      4.577955      -15.123080       30.656473                 0  27.389157  30.039733  -122.809507  177.587821           240
    25          25      3742402     3742402       6.832601      2.888758       -7.611187       21.276389                 0  31.916351  31.729109  -126.729193  190.561895             0
    26          26      3005648     3005623       6.570749      2.520561       -6.032056       19.173554                 0  26.320516  22.317805   -85.268509  137.909541            25
    27          27      9264824     9258452       8.743662      4.964863      -16.080652       33.567976                 0  25.419032  19.164357   -70.402754  121.240818          6372
    28          28      4654914     4654545       6.493017      2.910625       -8.060106       21.046141                 0  27.827170  19.575933   -70.052493  125.706832           369
    29          29      5828286     5828115       7.498484      4.159252      -13.297777       28.294744                 0  31.745953  59.089240  -263.700246  327.192152           171
    30          30      8719840     8719672       8.738283      5.684630      -19.684867       37.161433               168  72.333328  52.597008  -190.651711  335.318367             0
    31          31      8379588     8363422       7.701492      3.880669      -11.701855       27.104839                 0  61.275307 402.680797 -1952.128679 2074.679293         16166
    32          32      2877488     2877488       7.557505      4.354946      -14.217228       29.332237                 0  39.288698  36.463642  -143.029512  221.606907             0
    33          33      6346818     6346758       5.968882      4.081225      -14.437242       26.375006                 0  25.992455  28.561288  -116.813986  168.798896            60
    34          34      4092814     4092773       7.718702      3.129215       -7.927372       23.364777                 0  31.128155  30.802705  -122.885371  185.141680            41
    35          35      7404242     7404242       7.779768      4.363240      -14.036434       29.595970                 0  27.575819  38.082959  -162.838977  217.990614             0
    36          36      4092814     4092773       7.718702      3.129215       -7.927372       23.364777                 0  31.128155  30.802705  -122.885371  185.141680            41
    37          37      2167492     2167492       6.710608      3.841279      -12.495785       25.917001                 0  29.342509  28.658555  -113.950266  172.635285             0
    38          38      4450500     4450500       7.066185      3.674532      -11.306473       25.438844                 0  46.981200  42.683522  -166.436410  260.398811             0
    39          39      3482268     3482203       7.745833      2.672184       -5.615089       21.106755                 4  31.511083  21.133372   -74.155776  137.177943            61
    40          40      6184360     6184360       6.720673      5.357537      -20.067010       33.508357                 0  25.424385  35.082946  -149.990346  200.839116             0
    41          41      5173692     5173690       8.470649      6.245013      -22.754414       39.695711                 2  26.649386  32.369763  -135.199430  188.498203             0
    42          42     13813734    13813279       9.410336      4.917914      -15.179235       33.999907                 0  33.358796  58.175426  -257.518334  324.235925           455
    43          43     11943986    11943986      10.019476      7.131261      -25.636829       45.675780                 0  33.869077  31.797886  -125.120353  192.858506             0
    44          44     13031066    13030710       7.904029      3.973822      -11.965078       27.773137                 1  27.074212  29.127260  -118.562086  172.710511           355
    45          45      7507234     7507234       8.609286      4.839243      -15.586930       32.805502                 0  30.439763  35.870345  -148.911965  209.791490             0
    46          46      5010508     5010501       6.749890      4.181341      -14.156815       27.656595                 0  20.997423  27.546761  -116.736382  158.731228             7
    47          47      6683868     6683745       6.861464      3.165111       -8.964089       22.687017                 0  18.010699  31.109804  -137.538321  173.559720           123
    48          48      2289398     2289398       7.315893      4.351994      -14.444079       29.075865                 0  44.768846  40.776863  -159.115471  248.653162             0
    49          49      1979348     1979348       7.340024      3.819676      -11.758357       26.438404                 0  27.705926  33.450487  -139.546511  194.958363             0
    50          50      9609274     9609063       4.944994      1.815080       -4.130406       14.020393               198  43.411529  29.825439  -105.715665  192.538723            13
    51          51      8306932     8306925       6.596631      2.957330       -8.190021       21.383283                 7  28.400109  30.158562  -122.392703  179.192921             0
    52          52      2761542     2760728       6.260187      2.076494       -4.122285       16.642659                 0  26.879426  22.961888   -87.930016  141.688869           814
    53          53     12851432    12851432       8.202865      5.084118      -17.217725       33.623456                 0  23.032184  41.111310  -182.524364  228.588732             0
    54          54      7055956     7055956       8.155223      5.019885      -16.944201       33.254647                 0  31.991018  45.726951  -196.643739  260.625776             0
    55          55      8335400     8335400       7.011145      4.451551      -15.246608       29.268898                 0  30.556272  37.280262  -155.845039  216.957583             0
    56          56      3712608     3712606       7.327365      3.768064      -11.512954       26.167684                 0  42.247937  26.006330   -87.783711  172.279585             2
    57          57     40573822    40573820       7.748734      4.572174      -15.112136       30.609603                 0  32.485565  32.441973  -129.724299  194.695429             2
    58          58      9209132     9208264      10.918931      2.329201       -0.727075       22.564937                 2  42.959220  92.381700  -418.949282  504.867722           866
    59          59      5957758     5957485       9.165388      5.394796      -17.808593       36.139369                 0  41.109407  72.898647  -323.383830  405.602645           273
    60          60      6587080     6586816       8.946106      4.906866      -15.588225       33.480437               153  38.342976  49.461662  -208.965334  285.651287           111
    61          61      3466814     3466546       6.203642      4.268483      -15.138774       27.546058                 0  40.002926  27.087127   -95.432709  175.438561           268
    62          62      8556188     8518850       7.973005      3.859464      -11.324315       27.270324                 0  90.152104 603.163103 -2925.663412 3105.967621         37338
    63          63     10039914    10039914       6.780719      5.058563      -18.512096       32.073535                 0  27.589883  38.200537  -163.412801  218.592566             0
    64          64      6059974     6059974       6.861594      3.390932      -10.093068       23.816255                 0  34.205485  37.413520  -152.862116  221.273086             0
    65          65      4652914     4648028       7.341187      2.836768       -6.842653       21.525026                 0  30.311689  18.229901   -60.837814  121.461191          4886
    66          66      4332788     4332698       6.385402      4.588856      -16.558877       29.329682                 0  28.059763  28.720138  -115.540925  171.660451            90
    67          67      8663640     8601552      12.021037     54.366312     -259.810525      283.852599             35142  23.978340  15.848985   -55.266584  103.223264         26946
    68          68      5139952     5091939      16.924618     84.385583     -405.003296      438.852532             48013  34.254315  30.630432  -118.897843  187.406472             0
    69          69      4089682     4089675       6.017070      1.678900       -2.377431       14.411571                 7  40.788158  30.297722  -110.700452  192.276768             0
    70          70      7917244     7915563       7.561958      2.708821       -5.982147       21.106064                11  26.083079  26.720143  -107.517634  159.683793          1670
    71          71     13157840    13123389       9.523167     36.756506     -174.259363      193.305697             34451  26.904475  30.117076  -123.680903  177.489852             0
    72          72      4587208     4587176       5.795858      3.521992      -11.814101       23.405816                32  36.755295  42.361239  -175.050898  248.561489             0
    73          73      2783546     2780082       5.542128      3.064558       -9.780664       20.864920                 0  26.749666  21.452411   -80.512387  134.011719          3464
    74          74      7917982     7913090       7.431814      3.971284      -12.424605       27.288232                 0   7.061163  25.456280  -120.220237  134.342563          4892
    75          75     11943986    11943986      10.019476      7.131261      -25.636829       45.675780                 0  33.869077  31.797886  -125.120353  192.858506             0
    76          76     10563962    10563961      10.084792      7.245795      -26.144185       46.313769                 1  27.124666  28.219182  -113.971243  168.220576             0
    77          77      4004836     4004796       6.874677      4.692294      -16.586790       30.336145                 0  27.526195  30.750736  -126.227484  181.279875            40
    78          78      4327598     4327598       5.961276      3.430781      -11.192627       23.115179                 0  41.737961  34.314577  -129.834925  213.310846             0
    79          79      6676228     6675792       6.422877      4.404076      -15.597501       28.443255                 0  23.125674  29.601232  -124.880488  171.131836           436
    80          80      3724334     3724281       5.470541      2.967462       -9.366769       20.307850                34  25.370590  36.587532  -157.567070  208.308250            19
    81          81      6724412     6724060       6.061246      2.347224       -5.674874       17.797367                 0  24.632065  15.324676   -51.991313  101.255443           352
    82          82      8520406     8520406       7.376640      4.507111      -15.158914       29.912195                 0  36.090248  34.189937  -134.859435  207.039931             0
    83          83      3682726     3672473       4.828217      1.022750       -0.285534        9.941968                21  29.409355  25.045463   -95.817957  154.636668         10232
    84          84      5722452     5722450       6.455144      3.347878      -10.284246       23.194534                 2  33.033724  37.620518  -155.068866  221.136313             0
    85          85      7749260     7749260       6.948704      3.631841      -11.210501       25.107909                 0  40.321476  43.453693  -176.946988  257.589940             0
    86          87      2428326     2428298       8.723121      5.078477      -16.669262       34.115503                 0  32.929958  29.702407  -115.582077  181.441994            28

Saved outlier summary to: D:\Medical_AI\Data\processed\outlier_summary.csv

In [21]:
patient_dfs_list[70].shape

(13123389, 8)

In [20]:
for df in patient_dfs_list:
    pid = int(df['patient_id'].iloc[0])
    print(f"Patient {pid}:")
    print(df.iloc[[0]].to_string())
    print()

Patient 1:
                timestamp test_type  test_value  patient_id  label          start_date            end_date      machine_year_full
0 2023-10-02 01:04:20.200      flow       -38.4           1      0 2023-10-02 01:04:20 2023-11-06 08:58:10  B3A20604054_2023_good

Patient 2:
                timestamp test_type  test_value  patient_id  label          start_date            end_date      machine_year_full
0 2023-09-25 13:00:34.200      flow        52.6           2      0 2023-09-25 13:00:34 2023-10-31 22:17:08  B3A20605023_2023_good

Patient 3:
                timestamp test_type  test_value  patient_id  label          start_date            end_date      machine_year_full
0 2023-09-01 15:52:11.200      flow       -38.4           3      0 2023-09-01 15:52:11 2023-10-21 06:45:55  B3A20605070_2023_good

Patient 4:
                timestamp test_type  test_value  patient_id  label          start_date            end_date      machine_year_full
0 2024-12-01 08:11:47.200      flow        19.7           4      0 2024-12-01 08:11:47 2024-12-31 19:46:14  B3A23701088_2025_good

Patient 5:
                timestamp test_type  test_value  patient_id  label          start_date            end_date      machine_year_full
0 2024-12-01 07:10:23.200      flow        35.3           5      0 2024-12-01 07:10:23 2024-12-31 11:25:45  B3A23C26164_2025_good

Patient 6:
                timestamp test_type  test_value  patient_id  label          start_date            end_date      machine_year_full
0 2024-12-01 09:29:03.200      flow        15.4           6      0 2024-12-01 09:29:03 2024-12-31 13:29:03  B3A24606034_2025_good

Patient 7:
                timestamp test_type  test_value  patient_id  label          start_date            end_date      machine_year_full
0 2024-11-30 23:55:42.200      flow        -1.6           7      0 2024-11-30 23:55:42 2024-12-31 13:05:48  B3C23619117_2025_good

Patient 8:
                timestamp test_type  test_value  patient_id  label          start_date            end_date      machine_year_full
0 2024-11-30 23:07:17.200      flow        22.4           8      0 2024-11-30 23:07:17 2024-12-31 22:40:41  B3C23C24308_2025_good

Patient 9:
                timestamp test_type  test_value  patient_id  label          start_date            end_date      machine_year_full
0 2024-12-01 06:59:31.200      flow        16.7           9      0 2024-12-01 06:59:31 2024-12-31 14:45:09  B3C23C27141_2025_good

Patient 10:
                timestamp test_type  test_value  patient_id  label          start_date            end_date      machine_year_full
0 2024-12-01 10:33:47.200      flow       -30.3          10      0 2024-12-01 10:33:47 2024-12-31 12:41:03  B3C23C27371_2025_good

Patient 11:
                timestamp test_type  test_value  patient_id  label          start_date            end_date      machine_year_full
0 2024-12-01 04:28:47.200      flow        68.4          11      0 2024-12-01 04:28:47 2024-12-31 17:30:44  B3C24325207_2025_good

Patient 12:
                timestamp test_type  test_value  patient_id  label          start_date            end_date      machine_year_full
0 2024-11-04 23:41:16.200      flow       -38.4          12      0 2024-11-04 23:41:16 2024-12-05 22:07:58  B3C24329028_2024_good

Patient 13:
                timestamp test_type  test_value  patient_id  label          start_date            end_date      machine_year_full
0 2024-12-01 06:42:09.200      flow        75.2          13      0 2024-12-01 06:42:09 2024-12-31 13:38:55  B3C24406068_2025_good

Patient 14:
                timestamp test_type  test_value  patient_id  label          start_date            end_date      machine_year_full
0 2024-12-01 12:57:30.200      flow        20.2          14      0 2024-12-01 12:57:30 2024-12-31 22:22:12  B3C24513126_2025_good

Patient 15:
                timestamp test_type  test_value  patient_id  label          start_date            end_date      machine_year_full
0 2024-12-01 06:08:50.200      flow       -38.4          15      0 2024-12-01 06:08:50 2024-12-31 09:50:03  B3C24513203_2025_good

Patient 16:
                timestamp test_type  test_value  patient_id  label          start_date            end_date      machine_year_full
0 2024-12-01 10:49:41.200      flow        25.2          16      0 2024-12-01 10:49:41 2024-12-31 15:30:20  B3C24513221_2025_good

Patient 17:
                timestamp test_type  test_value  patient_id  label          start_date            end_date      machine_year_full
0 2024-12-01 09:59:32.200      flow       170.2          17      0 2024-12-01 09:59:32 2024-12-31 21:41:34  B3C24515251_2025_good

Patient 18:
                timestamp test_type  test_value  patient_id  label          start_date            end_date      machine_year_full
0 2024-12-01 14:04:21.200      flow        86.9          18      0 2024-12-01 14:04:21 2024-12-31 18:12:56  B3C24518077_2025_good

Patient 19:
                timestamp test_type  test_value  patient_id  label          start_date            end_date      machine_year_full
0 2024-12-01 09:36:30.200      flow        20.9          19      0 2024-12-01 09:36:30 2024-12-31 20:15:19  B3C24623101_2025_good

Patient 20:
                timestamp test_type  test_value  patient_id  label          start_date            end_date      machine_year_full
0 2024-12-01 20:41:50.200      flow       -38.4          20      0 2024-12-01 20:41:50 2024-12-31 13:12:06  B3C24623207_2025_good

Patient 21:
                timestamp test_type  test_value  patient_id  label          start_date            end_date      machine_year_full
0 2024-12-01 06:20:16.200      flow        65.4          21      0 2024-12-01 06:20:16 2024-12-31 11:08:57  B3C24702027_2025_good

Patient 22:
                timestamp test_type  test_value  patient_id  label          start_date            end_date      machine_year_full
0 2024-12-01 14:42:46.200      flow        21.4          22      0 2024-12-01 14:42:46 2024-12-31 12:39:35  B3CBD605550_2025_good

Patient 23:
                timestamp test_type  test_value  patient_id  label          start_date            end_date      machine_year_full
0 2024-12-01 08:57:18.200      flow        26.0          23      0 2024-12-01 08:57:18 2024-12-31 22:59:59  B3CBD607039_2025_good

Patient 24:
                timestamp test_type  test_value  patient_id  label          start_date            end_date      machine_year_full
0 2024-12-01 03:46:54.200      flow       -38.4          24      0 2024-12-01 03:46:54 2024-12-31 18:54:52  B3CBD801013_2025_good

Patient 25:
                timestamp test_type  test_value  patient_id  label          start_date            end_date      machine_year_full
0 2023-09-13 12:58:01.200      flow        22.8          25      0 2023-09-13 12:58:01 2023-11-06 11:59:59  B3D21705058_2023_good

Patient 26:
                timestamp test_type  test_value  patient_id  label          start_date            end_date      machine_year_full
0 2024-12-01 09:43:12.200      flow        66.5          26      0 2024-12-01 09:43:12 2024-12-31 12:19:49  B3D24403103_2025_good

Patient 27:
                timestamp test_type  test_value  patient_id  label          start_date            end_date      machine_year_full
0 2023-10-01 17:14:01.200      flow       -19.5          27      0 2023-10-01 17:14:01 2023-11-06 08:24:35  Y2A17601035_2023_good

Patient 28:
                timestamp test_type  test_value  patient_id  label          start_date            end_date      machine_year_full
0 2023-10-08 19:05:44.200      flow       -38.4          28      0 2023-10-08 19:05:44 2023-11-11 01:10:10  Y2A18105007_2023_good

Patient 29:
                timestamp test_type  test_value  patient_id  label          start_date            end_date      machine_year_full
0 2024-12-01 08:51:05.200      flow         7.0          29      0 2024-12-01 08:51:05 2024-12-31 19:12:03  Y2A18105058_2025_good

Patient 30:
                timestamp test_type  test_value  patient_id  label          start_date            end_date      machine_year_full
0 2023-10-01 23:01:23.200      flow       105.0          30      0 2023-10-01 23:01:23 2023-11-06 05:51:17  Y2A18301033_2023_good

Patient 31:
                timestamp test_type  test_value  patient_id  label          start_date            end_date      machine_year_full
0 2024-03-14 23:20:02.200      flow       170.6          31      0 2024-03-14 23:20:02 2024-04-15 18:43:18  Y2A18301034_2024_good

Patient 32:
                timestamp test_type  test_value  patient_id  label          start_date            end_date      machine_year_full
0 2023-10-01 19:43:03.200      flow        69.3          32      0 2023-10-01 19:43:03 2023-11-06 10:17:26  Y2A18C03159_2023_good

Patient 33:
                timestamp test_type  test_value  patient_id  label          start_date            end_date      machine_year_full
0 2024-12-01 12:27:22.200      flow       -11.1          33      0 2024-12-01 12:27:22 2024-12-31 17:54:00  Y2A20205196_2025_good

Patient 34:
                timestamp test_type  test_value  patient_id  label          start_date            end_date      machine_year_full
0 2023-10-01 20:51:21.200      flow       -38.4          34      0 2023-10-01 20:51:21 2023-11-05 22:27:02  Y2A20B03088_2023_good

Patient 35:
                timestamp test_type  test_value  patient_id  label          start_date            end_date      machine_year_full
0 2024-12-01 07:10:19.200      flow       -38.4          35      0 2024-12-01 07:10:19 2024-12-31 08:15:16  Y2A21607360_2025_good

Patient 36:
                timestamp test_type  test_value  patient_id  label          start_date            end_date      machine_year_full
0 2023-10-01 20:51:21.200      flow       -38.4          36      0 2023-10-01 20:51:21 2023-11-05 22:27:02  Y2A21901468_2023_good

Patient 37:
                timestamp test_type  test_value  patient_id  label          start_date            end_date      machine_year_full
0 2024-12-01 00:24:41.200      flow        20.0          37      0 2024-12-01 00:24:41 2024-12-31 21:36:59  Y2A21A02145_2025_good

Patient 38:
                timestamp test_type  test_value  patient_id  label          start_date            end_date      machine_year_full
0 2024-12-01 08:16:37.200      flow        10.0          38      0 2024-12-01 08:16:37 2024-12-31 17:18:01  Y2A23402121_2025_good

Patient 39:
                timestamp test_type  test_value  patient_id  label          start_date            end_date      machine_year_full
0 2024-12-01 07:51:41.200      flow       -38.4          39      0 2024-12-01 07:51:41 2024-12-31 17:47:29  Y2A23A01223_2025_good

Patient 40:
                timestamp test_type  test_value  patient_id  label          start_date            end_date      machine_year_full
0 2024-11-30 23:00:00.200      flow        10.0          40      0 2024-11-30 23:00:00 2024-12-31 12:55:37  Y2A24306219_2025_good

Patient 41:
                timestamp test_type  test_value  patient_id  label          start_date            end_date      machine_year_full
0 2023-06-01 12:00:00.200      flow         6.0          41      0 2023-06-01 12:00:00 2023-07-11 11:59:59  Y2C16702047_2023_good

Patient 42:
                timestamp test_type  test_value  patient_id  label          start_date            end_date      machine_year_full
0 2023-10-01 15:04:58.200      flow        90.8          42      0 2023-10-01 15:04:58 2023-11-06 10:39:47  Y2C17902004_2023_good

Patient 43:
                timestamp test_type  test_value  patient_id  label          start_date            end_date     machine_year_full
0 2023-03-04 23:03:59.200      flow         1.6          43      0 2023-06-01 23:01:08 2023-07-11 08:55:17  Y2C19408118_2023_bad

Patient 44:
                timestamp test_type  test_value  patient_id  label          start_date            end_date      machine_year_full
0 2023-05-01 12:00:00.200      flow        51.9          44      0 2023-05-01 12:00:00 2023-06-10 11:59:59  Y2C21604310_2023_good

Patient 45:
                timestamp test_type  test_value  patient_id  label          start_date            end_date      machine_year_full
0 2024-12-01 00:01:50.200      flow       -13.2          45      0 2024-12-01 00:01:50 2024-12-31 12:51:12  Y2C21A01536_2025_good

Patient 46:
                timestamp test_type  test_value  patient_id  label          start_date            end_date      machine_year_full
0 2024-12-01 07:27:25.200      flow       -38.4          46      0 2024-12-01 07:27:25 2024-12-31 18:00:08  Y2C23103527_2025_good

Patient 47:
                timestamp test_type  test_value  patient_id  label          start_date            end_date      machine_year_full
0 2023-10-01 22:35:05.200      flow       -38.4          47      0 2023-10-01 22:35:05 2023-11-06 06:00:08  Y2D21105246_2023_good

Patient 48:
                timestamp test_type  test_value  patient_id  label          start_date            end_date      machine_year_full
0 2024-12-01 04:28:26.200      flow       139.5          48      0 2024-12-01 04:28:26 2024-12-31 11:23:58  Y2D24603180_2025_good

Patient 49:
                timestamp test_type  test_value  patient_id  label          start_date            end_date      machine_year_full
0 2024-12-01 19:56:36.200      flow        77.8          49      0 2024-12-01 19:56:36 2024-12-31 18:17:18  YSA22C14327_2025_good

Patient 50:
                timestamp test_type  test_value  patient_id  label          start_date            end_date      machine_year_full
0 2024-12-01 14:58:25.200      flow        75.0          50      0 2024-12-01 14:58:25 2024-12-31 22:59:59  YSA23120560_2025_good

Patient 51:
                timestamp test_type  test_value  patient_id  label          start_date            end_date      machine_year_full
0 2023-02-21 12:25:13.200      flow        -1.3          51      0 2023-02-21 12:25:13 2023-03-26 14:15:12  YSB21607337_2023_good

Patient 52:
                timestamp test_type  test_value  patient_id  label          start_date            end_date      machine_year_full
0 2023-04-16 00:50:15.200      flow       -38.4          52      0 2023-04-16 00:50:15 2023-05-08 07:27:22  YSB22707063_2023_good

Patient 53:
                timestamp test_type  test_value  patient_id  label          start_date            end_date      machine_year_full
0 2023-10-01 12:00:00.200      flow         1.6          53      0 2023-10-01 12:00:00 2023-11-06 07:48:43  YSB23114301_2023_good

Patient 54:
                timestamp test_type  test_value  patient_id  label          start_date            end_date      machine_year_full
0 2024-12-01 02:25:13.200      flow         1.6          54      0 2024-12-01 02:25:13 2024-12-31 22:08:16  YSB23114301_2025_good

Patient 55:
                timestamp test_type  test_value  patient_id  label          start_date            end_date      machine_year_full
0 2023-10-01 12:00:00.200      flow         8.0          55      0 2023-10-01 12:00:00 2023-11-06 11:59:59  YSB23122623_2023_good

Patient 56:
                timestamp test_type  test_value  patient_id  label          start_date            end_date      machine_year_full
0 2024-12-01 09:46:14.200      flow         2.5          56      0 2024-12-01 09:46:14 2024-12-31 17:53:43  YSC22408582_2025_good

Patient 57:
                timestamp test_type  test_value  patient_id  label          start_date            end_date      machine_year_full
0 2023-06-05 11:24:24.200      flow         2.5          57      0 2023-06-05 11:24:24 2023-11-06 03:26:48  YSE23104366_2023_good

Patient 58:
                timestamp test_type  test_value  patient_id  label          start_date            end_date     machine_year_full
0 2021-09-10 14:11:45.200      flow       -18.4          58      1 2021-09-10 14:11:45 2021-10-11 10:04:14  B3320402093_2023_bad

Patient 59:
                timestamp test_type  test_value  patient_id  label          start_date            end_date     machine_year_full
0 2024-11-01 02:26:18.200      flow        76.6          59      1 2024-11-01 02:26:18 2024-11-30 03:33:36  B3C21201347_2024_bad

Patient 60:
                timestamp test_type  test_value  patient_id  label          start_date            end_date     machine_year_full
0 2023-06-20 20:57:20.200      flow       -38.4          60      1 2023-06-20 20:57:20 2023-07-24 06:49:27  B3C21401167_2023_bad

Patient 61:
                timestamp test_type  test_value  patient_id  label          start_date            end_date     machine_year_full
0 2024-10-01 01:40:21.200      flow       -38.4          61      1 2024-10-01 01:40:21 2024-11-10 18:29:58  B3C23C03251_2024_bad

Patient 62:
                timestamp test_type  test_value  patient_id  label          start_date            end_date     machine_year_full
0 2023-02-28 13:06:12.200      flow       -38.4          62      1 2023-02-28 13:06:12 2023-03-29 07:55:13  Y2A18301034_2023_bad

Patient 63:
                timestamp test_type  test_value  patient_id  label          start_date            end_date     machine_year_full
0 2019-11-28 22:11:35.200      flow       156.9          63      1 2019-11-28 22:11:35 2019-12-28 06:41:05  Y2A19102026_2023_bad

Patient 64:
                timestamp test_type  test_value  patient_id  label          start_date            end_date     machine_year_full
0 2023-04-20 22:20:31.200      flow       -38.4          64      1 2023-04-20 22:20:31 2023-05-19 08:10:56  Y2A20703184_2023_bad

Patient 65:
                timestamp test_type  test_value  patient_id  label          start_date            end_date     machine_year_full
0 2021-12-15 21:45:01.200      flow         4.1          65      1 2021-12-15 21:45:01 2022-01-14 07:04:23  Y2A20705285_2023_bad

Patient 66:
                timestamp test_type  test_value  patient_id  label          start_date            end_date     machine_year_full
0 2021-10-08 02:59:31.200      flow        13.3          66      1 2021-10-08 02:59:31 2021-11-04 01:58:15  Y2A20B03100_2023_bad

Patient 67:
                timestamp test_type  test_value  patient_id  label          start_date            end_date     machine_year_full
0 2022-11-10 22:46:28.200      flow       -38.4          67      1 2022-11-10 22:46:28 2022-12-11 23:25:16  Y2A21104526_2023_bad

Patient 68:
                timestamp test_type  test_value  patient_id  label          start_date            end_date     machine_year_full
0 2021-09-07 12:00:00.200      flow        37.5          68      1 2021-09-07 12:00:00 2021-10-07 11:12:22  Y2A21106018_2023_bad

Patient 69:
                timestamp test_type  test_value  patient_id  label          start_date            end_date     machine_year_full
0 2021-12-06 13:11:27.200      flow        14.4          69      1 2021-12-06 13:11:27 2022-01-06 06:14:51  Y2A21606379_2023_bad

Patient 70:
                timestamp test_type  test_value  patient_id  label          start_date            end_date     machine_year_full
0 2023-03-02 12:11:59.200      flow         2.5          70      1 2023-03-02 12:11:59 2023-04-02 08:22:29  Y2A21B01199_2023_bad

Patient 71:
                timestamp test_type  test_value  patient_id  label          start_date            end_date     machine_year_full
0 2023-06-21 23:00:00.200      flow        55.9          71      1 2023-06-21 23:00:00 2023-07-22 22:59:59  Y2A22402014_2024_bad

Patient 72:
                timestamp test_type  test_value  patient_id  label          start_date            end_date     machine_year_full
0 2022-12-08 09:52:55.200      flow       -38.4          72      1 2022-12-08 09:52:55 2022-12-30 20:53:22  Y2A22602589_2023_bad

Patient 73:
                timestamp test_type  test_value  patient_id  label          start_date            end_date     machine_year_full
0 2023-04-15 08:46:34.200      flow       -38.4          73      1 2023-04-15 08:46:34 2023-05-08 16:15:38  Y2A22C03150_2023_bad

Patient 74:

Step 1.4 Add countdown & drop label 0 (optional)

In [43]:
import pandas as pd
import numpy as np
from tqdm import tqdm
import gc

def process_and_cut_7days_inplace(patient_dfs_list):
    """
    For ALL patients (label 0 and label 1):
      1. Coerce & validate timestamps
      2. Cut to last 7*24h window (countdown days 0..6)
      3. Add features relative to first actual recorded timestamp in window
    Mutates patient_dfs_list in place; returns None.
    """
    kept = []

    for i, df in tqdm(enumerate(patient_dfs_list, start=1), desc="Enriching & cutting 7 days"):
        if not isinstance(df, pd.DataFrame) or df.empty or 'label' not in df.columns:
            continue
        if 'timestamp' not in df.columns:
            continue

        # Coerce datetimes
        df['timestamp'] = pd.to_datetime(df['timestamp'], errors='coerce')
        if 'start_date' in df.columns:
            df['start_date'] = pd.to_datetime(df['start_date'], errors='coerce')
        if 'end_date' in df.columns:
            df['end_date'] = pd.to_datetime(df['end_date'], errors='coerce')

        # Boolean mask to avoid MemoryError from dropna inplace
        need_cols = ['timestamp']
        if 'start_date' in df.columns: need_cols.append('start_date')
        if 'end_date'   in df.columns: need_cols.append('end_date')
        mask = df[need_cols].notna().all(axis=1)
        if not mask.all():
            df = df.loc[mask].reset_index(drop=True)
        if df.empty:
            continue

        # Patient-level end date
        end0 = df['end_date'].dropna().iloc[0] if 'end_date' in df.columns and df['end_date'].notna().any() else pd.NaT
        if pd.isna(end0):
            continue

        # Sort
        df = df.sort_values('timestamp', kind='mergesort').reset_index(drop=True)

        # ✅ +1 second on start_ts so floor((end_ts - start_ts) / 86400) = 6, never 7
        end_ts   = end0
        start_ts = end_ts - pd.Timedelta(days=7) + pd.Timedelta(seconds=1)

        window_mask = (df['timestamp'] >= start_ts) & (df['timestamp'] <= end_ts)
        df = df.loc[window_mask].reset_index(drop=True)
        if df.empty:
            continue

        ts = df['timestamp']

        # Countdown: floor((end_ts - timestamp) / 86400), guaranteed 0..6
        seconds_left = (end_ts - ts).dt.total_seconds()
        countdown    = np.floor(seconds_left / 86400.0).astype('int32')

        # Sanity check — should never trigger with +1s fix
        cd_min, cd_max = int(countdown.min()), int(countdown.max())
        pid = df['patient_id'].iloc[0] if 'patient_id' in df.columns else i
        if cd_min < 0 or cd_max > 6:
            print(f"⚠️  Patient {pid}: countdown {cd_min}..{cd_max} still out of [0..6] — skipping")
            continue

        # ✅ Use first actual recorded timestamp as reference (patient may not use machine every hour)
        actual_start = ts.min()

        # Features
        df['start_date']                = actual_start
        df['delta_time_seconds']        = ts.diff().dt.total_seconds().fillna(0).clip(lower=0)
        df['time_from_start_seconds']   = (ts - actual_start).dt.total_seconds()  # 0 at first row
        df['patient_span_days']         = (ts.max() - ts.min()).total_seconds() / 86400.0  # actual span
        df['hour_of_day']               = ts.dt.hour
        df['hour_of_day_scaled']        = df['hour_of_day'] / 24.0
        df['countdown_days_target']     = countdown
        df['countdown_days_log_target'] = np.log2(1.0 + countdown.astype('float32'))

        kept.append(df)
        del ts, seconds_left, countdown, actual_start
        gc.collect()

    patient_dfs_list[:] = kept
    del kept
    gc.collect()
    return None

In [44]:
process_and_cut_7days_inplace(patient_dfs_list)
gc.collect()

print(f"Total patients: {len(patient_dfs_list)}")

# Sanity check
label_counts = {0: 0, 1: 0}
for df in patient_dfs_list:
    label_counts[int(df['label'].iloc[0])] += 1
print(f"Label 0: {label_counts[0]} patients, Label 1: {label_counts[1]} patients")

# Peek at one patient
sample = patient_dfs_list[0]
print(f"\n── Patient {sample['patient_id'].iloc[0]} ──")
print(f"  rows          : {len(sample)}")
print(f"  start_date    : {sample['start_date'].iloc[0]}")    # should match first timestamp
print(f"  end_date      : {sample['end_date'].iloc[0]}")
print(f"  span          : {sample['patient_span_days'].iloc[0]:.3f} days")
print(f"  countdown     : {sample['countdown_days_target'].min()}..{sample['countdown_days_target'].max()}")
print(f"  time_from_start first/last: {sample['time_from_start_seconds'].iloc[0]} / {sample['time_from_start_seconds'].iloc[-1]:.1f}")
print(sample[['timestamp', 'start_date', 'countdown_days_target', 'time_from_start_seconds', 'patient_span_days']].head(3))
print("...")
print(sample[['timestamp', 'start_date', 'countdown_days_target', 'time_from_start_seconds', 'patient_span_days']].tail(3))

Enriching & cutting 7 days: 85it [00:53,  1.58it/s]

Total patients: 85
Label 0: 56 patients, Label 1: 29 patients

── Patient 1 ──
  rows          : 1538815
  start_date    : 2023-10-30 22:59:40.200000
  end_date      : 2023-11-06 08:58:10
  span          : 6.416 days
  countdown     : 0..6
  time_from_start first/last: 0.0 / 554309.8
                timestamp              start_date  countdown_days_target  \
0 2023-10-30 22:59:40.200 2023-10-30 22:59:40.200                      6
1 2023-10-30 22:59:40.200 2023-10-30 22:59:40.200                      6
2 2023-10-30 22:59:40.400 2023-10-30 22:59:40.200                      6

   time_from_start_seconds  patient_span_days
0                      0.0           6.415623
1                      0.0           6.415623
2                      0.2           6.415623
...
                      timestamp              start_date  \
1538812 2023-11-06 08:58:09.800 2023-10-30 22:59:40.200
1538813 2023-11-06 08:58:10.000 2023-10-30 22:59:40.200
1538814 2023-11-06 08:58:10.000 2023-10-30 22:59:40.200

         countdown_days_target  time_from_start_seconds  patient_span_days
1538812                      0                 554309.6           6.415623
1538813                      0                 554309.8           6.415623
1538814                      0                 554309.8           6.415623

In [45]:
print(len(patient_dfs_list))

85

In [46]:
patient_dfs_list[28].head()

,timestamp,test_type,test_value,patient_id,label,start_date,end_date,machine_year_full,delta_time_seconds,time_from_start_seconds,patient_span_days,hour_of_day,hour_of_day_scaled,countdown_days_target,countdown_days_log_target
0,2024-12-25 10:03:01.200,pressure,0.0,29,0,2024-12-25 10:03:01.200,2024-12-31 19:12:03,Y2A18105058_2025_good,0.0,0.0,6.381271,10,0.416667,6,2.807355
1,2024-12-25 10:03:01.200,flow,-38.4,29,0,2024-12-25 10:03:01.200,2024-12-31 19:12:03,Y2A18105058_2025_good,0.0,0.0,6.381271,10,0.416667,6,2.807355
2,2024-12-25 10:03:01.400,flow,-38.4,29,0,2024-12-25 10:03:01.200,2024-12-31 19:12:03,Y2A18105058_2025_good,0.2,0.2,6.381271,10,0.416667,6,2.807355
3,2024-12-25 10:03:01.400,pressure,0.0,29,0,2024-12-25 10:03:01.200,2024-12-31 19:12:03,Y2A18105058_2025_good,0.0,0.2,6.381271,10,0.416667,6,2.807355
4,2024-12-25 10:03:01.600,flow,-38.4,29,0,2024-12-25 10:03:01.200,2024-12-31 19:12:03,Y2A18105058_2025_good,0.2,0.4,6.381271,10,0.416667,6,2.807355

# add log for target

In [18]:
patient_dfs_list[1].head(5)

,timestamp,test_type,test_value,patient_id,label,start_date,end_date,machine_year_full,delta_time_seconds,time_from_start_seconds,patient_span_days,countdown_days_target,hour_of_day,hour_of_day_scaled,countdown_days_log_target
0,2024-11-01 02:26:18.200,flow,76.60,59,1,2024-11-01 02:26:18,2024-11-30 03:33:36,B3C21201347_2024_bad,0.0,0.2,29.046736,30,2,0.083333,3.433987
1,2024-11-01 02:26:18.200,pressure,10.25,59,1,2024-11-01 02:26:18,2024-11-30 03:33:36,B3C21201347_2024_bad,0.0,0.2,29.046736,30,2,0.083333,3.433987
2,2024-11-01 02:26:18.400,flow,121.60,59,1,2024-11-01 02:26:18,2024-11-30 03:33:36,B3C21201347_2024_bad,0.2,0.4,29.046736,30,2,0.083333,3.433987
3,2024-11-01 02:26:18.400,pressure,16.56,59,1,2024-11-01 02:26:18,2024-11-30 03:33:36,B3C21201347_2024_bad,0.0,0.4,29.046736,30,2,0.083333,3.433987
4,2024-11-01 02:26:18.600,flow,135.50,59,1,2024-11-01 02:26:18,2024-11-30 03:33:36,B3C21201347_2024_bad,0.2,0.6,29.046736,30,2,0.083333,3.433987

Step 1.5 split into train val test based on pre-defined set

In [48]:
import pandas as pd

# Define path
file_path_split = r"D:\Medical_AI\Data\df_split.csv"

# Load the split dataframe
df_split = pd.read_csv(file_path_split)

# Quick check
print(df_split.head(5))

   patient_id  label collection
0           1      0       test
1           2      0      train
2           3      0      train
3           4      0        val
4           5      0        val

In [49]:
import pandas as pd

# 1) Build a mapping: patient_id -> collection
split_map = dict(
    zip(
        df_split['patient_id'].astype(int),
        df_split['collection'].astype(str)
    )
)

# 2) Route each patient's DataFrame into train/val/test lists
train_list, val_list, test_list = [], [], []
missing_in_split = []  # patient_ids not found in df_split

for df in patient_dfs_list:
    if not isinstance(df, pd.DataFrame) or df.empty or 'patient_id' not in df.columns:
        continue

    # patient_id should be constant within each patient's DataFrame; take first row
    pid = int(df['patient_id'].iloc[0])

    coll = split_map.get(pid, None)
    if coll is None:
        missing_in_split.append(pid)
        continue

    if coll == 'train':
        train_list.append(df)
    elif coll == 'val':
        val_list.append(df)
    elif coll == 'test':
        test_list.append(df)
    else:
        # Unknown label in df_split['collection']; skip or handle as needed
        missing_in_split.append(pid)

print(f"Patients routed -> train: {len(train_list)}, val: {len(val_list)}, test: {len(test_list)}")
if missing_in_split:
    print("Patient IDs missing or unknown in df_split:", sorted(set(missing_in_split)))

Patients routed -> train: 48, val: 15, test: 22

In [50]:
df_train = pd.concat(train_list, ignore_index=True) if train_list else pd.DataFrame()
df_val   = pd.concat(val_list,   ignore_index=True) if val_list   else pd.DataFrame()
df_test  = pd.concat(test_list,  ignore_index=True) if test_list  else pd.DataFrame()

print(len(df_train), len(df_val), len(df_test))

70587703 20671364 26861042

In [51]:
df_test.sample(5)

,timestamp,test_type,test_value,patient_id,label,start_date,end_date,machine_year_full,delta_time_seconds,time_from_start_seconds,patient_span_days,hour_of_day,hour_of_day_scaled,countdown_days_target,countdown_days_log_target
20369237,2024-12-28 17:36:59.800,pressure,14.19,56,0,2024-12-24 17:53:44.000,2024-12-31 17:53:43,YSC22408582_2025_good,0.0,344595.8,6.999988,17,0.708333,3,2.000000
14880892,2024-12-26 02:56:48.600,flow,79.00,40,0,2024-12-24 22:29:50.200,2024-12-31 12:55:37,Y2A24306219_2025_good,0.0,102418.4,6.601236,2,0.083333,5,2.584962
9763493,2024-12-31 06:56:53.800,flow,59.70,24,0,2024-12-24 18:54:53.000,2024-12-31 18:54:52,B3CBD801013_2025_good,0.2,561720.8,6.999988,6,0.250000,0,0.000000
14687429,2024-12-25 09:47:42.400,pressure,4.08,40,0,2024-12-24 22:29:50.200,2024-12-31 12:55:37,Y2A24306219_2025_good,0.2,40672.2,6.601236,9,0.375000,6,2.807355
22464327,2021-12-31 16:53:24.400,pressure,5.13,69,1,2021-12-30 07:36:00.200,2022-01-06 06:14:51,Y2A21606379_2023_bad,0.2,119844.2,6.943644,16,0.666667,5,2.584962

In [52]:
df_train.head(5)

,timestamp,test_type,test_value,patient_id,label,start_date,end_date,machine_year_full,delta_time_seconds,time_from_start_seconds,patient_span_days,hour_of_day,hour_of_day_scaled,countdown_days_target,countdown_days_log_target
0,2023-10-25 13:04:44.200,pressure,5.37,2,0,2023-10-25 13:04:44.200,2023-10-31 22:17:08,B3A20605023_2023_good,0.0,0.0,6.383609,13,0.541667,6,2.807355
1,2023-10-25 13:04:44.200,flow,77.70,2,0,2023-10-25 13:04:44.200,2023-10-31 22:17:08,B3A20605023_2023_good,0.0,0.0,6.383609,13,0.541667,6,2.807355
2,2023-10-25 13:04:44.400,flow,-37.80,2,0,2023-10-25 13:04:44.200,2023-10-31 22:17:08,B3A20605023_2023_good,0.2,0.2,6.383609,13,0.541667,6,2.807355
3,2023-10-25 13:04:44.400,pressure,4.04,2,0,2023-10-25 13:04:44.200,2023-10-31 22:17:08,B3A20605023_2023_good,0.0,0.2,6.383609,13,0.541667,6,2.807355
4,2023-10-25 13:04:44.600,pressure,3.78,2,0,2023-10-25 13:04:44.200,2023-10-31 22:17:08,B3A20605023_2023_good,0.2,0.4,6.383609,13,0.541667,6,2.807355

Step 1.6 MinMax Scaling

(1) scaling for countdown-days_target(y)

In [53]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np

# Column to scale
TARGET_COL = 'countdown_days_target'
SCALED_COL = f'{TARGET_COL}_scaled'

# 1) Fit on TRAIN only (drop NaNs to avoid fitting issues)
target_scaler = MinMaxScaler()
train_target = df_train[[TARGET_COL]].astype('float64')
target_scaler.fit(train_target.dropna())

# 2) Transform each split
for df in (df_train, df_val, df_test):
    # ensure float dtype; preserve NaNs
    x = df[[TARGET_COL]].astype('float64')
    # transform returns ndarray, align back to index
    df[SCALED_COL] = np.nan
    non_na_mask = x[TARGET_COL].notna()
    if non_na_mask.any():
        df.loc[non_na_mask, SCALED_COL] = target_scaler.transform(x.loc[non_na_mask, [TARGET_COL]])

# Quick check
print(df_train[[TARGET_COL, SCALED_COL]].head())
print(df_val[[TARGET_COL, SCALED_COL]].head())
print(df_test[[TARGET_COL, SCALED_COL]].head())

   countdown_days_target  countdown_days_target_scaled
0                      6                           1.0
1                      6                           1.0
2                      6                           1.0
3                      6                           1.0
4                      6                           1.0
   countdown_days_target  countdown_days_target_scaled
0                      6                           1.0
1                      6                           1.0
2                      6                           1.0
3                      6                           1.0
4                      6                           1.0
   countdown_days_target  countdown_days_target_scaled
0                      6                           1.0
1                      6                           1.0
2                      6                           1.0
3                      6                           1.0
4                      6                           1.0

In [54]:
df_train.head(5)

,timestamp,test_type,test_value,patient_id,label,start_date,end_date,machine_year_full,delta_time_seconds,time_from_start_seconds,patient_span_days,hour_of_day,hour_of_day_scaled,countdown_days_target,countdown_days_log_target,countdown_days_target_scaled
0,2023-10-25 13:04:44.200,pressure,5.37,2,0,2023-10-25 13:04:44.200,2023-10-31 22:17:08,B3A20605023_2023_good,0.0,0.0,6.383609,13,0.541667,6,2.807355,1.0
1,2023-10-25 13:04:44.200,flow,77.70,2,0,2023-10-25 13:04:44.200,2023-10-31 22:17:08,B3A20605023_2023_good,0.0,0.0,6.383609,13,0.541667,6,2.807355,1.0
2,2023-10-25 13:04:44.400,flow,-37.80,2,0,2023-10-25 13:04:44.200,2023-10-31 22:17:08,B3A20605023_2023_good,0.2,0.2,6.383609,13,0.541667,6,2.807355,1.0
3,2023-10-25 13:04:44.400,pressure,4.04,2,0,2023-10-25 13:04:44.200,2023-10-31 22:17:08,B3A20605023_2023_good,0.0,0.2,6.383609,13,0.541667,6,2.807355,1.0
4,2023-10-25 13:04:44.600,pressure,3.78,2,0,2023-10-25 13:04:44.200,2023-10-31 22:17:08,B3A20605023_2023_good,0.2,0.4,6.383609,13,0.541667,6,2.807355,1.0

In [55]:
# Print min and max used for scaling
min_val = target_scaler.data_min_[0]
max_val = target_scaler.data_max_[0]

print(f"Min target (days): {min_val}")
print(f"Max target (days): {max_val}")

Min target (days): 0.0
Max target (days): 6.0

In [56]:
df_train.sample(10)

,timestamp,test_type,test_value,patient_id,label,start_date,end_date,machine_year_full,delta_time_seconds,time_from_start_seconds,patient_span_days,hour_of_day,hour_of_day_scaled,countdown_days_target,countdown_days_log_target,countdown_days_target_scaled
52351955,2022-12-10 23:36:51.400,pressure,5.86,67,1,2022-12-04 23:25:17.000,2022-12-11 23:25:16,Y2A21104526_2023_bad,0.2,519094.4,6.999988,23,0.958333,0,0.000000,0.000000
23701592,2023-07-10 23:43:05.800,pressure,3.94,41,0,2023-07-04 20:10:57.200,2023-07-11 11:59:59,Y2C16702047_2023_good,0.0,531128.6,6.659049,23,0.958333,0,0.000000,0.000000
6448713,2024-12-24 23:03:39.800,pressure,11.60,8,0,2024-12-24 22:40:42.000,2024-12-31 22:40:41,B3C23C24308_2025_good,0.0,1377.8,6.999988,23,0.958333,6,2.807355,1.000000
27689363,2024-12-30 00:56:04.400,flow,23.00,45,0,2024-12-24 12:53:10.200,2024-12-31 12:51:12,Y2C21A01536_2025_good,0.0,475374.2,6.998632,0,0.000000,1,1.000000,0.166667
40199596,2021-10-11 09:27:30.800,flow,35.50,58,1,2021-10-04 10:37:17.200,2021-10-11 10:04:14,B3320402093_2023_bad,0.2,600613.6,6.977046,9,0.375000,0,0.000000,0.000000
7185160,2024-12-27 11:59:08.800,pressure,6.51,8,0,2024-12-24 22:40:42.000,2024-12-31 22:40:41,B3C23C24308_2025_good,0.2,220706.8,6.999988,11,0.458333,4,2.321928,0.666667
28094553,2023-10-31 00:50:59.600,pressure,5.09,47,0,2023-10-30 22:55:16.200,2023-11-06 06:00:08,Y2D21105246_2023_good,0.2,6943.4,6.295044,0,0.000000,6,2.807355,1.000000
39502472,2021-10-09 09:51:38.000,pressure,10.45,58,1,2021-10-04 10:37:17.200,2021-10-11 10:04:14,B3320402093_2023_bad,0.0,429260.8,6.977046,9,0.375000,2,1.584962,0.333333
69732180,2024-01-26 18:33:18.200,pressure,3.14,84,1,2024-01-22 09:13:50.200,2024-01-28 20:07:57,YSD21503317_2024_bad,0.0,379168.0,6.454245,18,0.750000,2,1.584962,0.333333
61314188,2021-04-09 21:44:03.800,pressure,4.09,79,1,2021-04-07 00:10:40.000,2021-04-14 00:10:39,Y2D20215150_2023_bad,0.2,250403.8,6.999988,21,0.875000,4,2.321928,0.666667

(1.5) scaling for countdown_days_log_target

In [57]:
from sklearn.preprocessing import MinMaxScaler

# Refit the scaler only on valid target range (label ≠ 0 already applied)
log_target_scaler = MinMaxScaler()
log_target_scaler.fit(df_train[['countdown_days_log_target']])  # Automatically uses min/max from real targets

# Apply to all splits
df_train['countdown_days_log_target_scaled'] = log_target_scaler.transform(df_train[['countdown_days_log_target']])
df_val['countdown_days_log_target_scaled'] = log_target_scaler.transform(df_val[['countdown_days_log_target']])
df_test['countdown_days_log_target_scaled'] = log_target_scaler.transform(df_test[['countdown_days_log_target']])

In [58]:
# Print min and max used for scaling
min_val_log = log_target_scaler.data_min_[0]
max_val_log = log_target_scaler.data_max_[0]

print(f"Min target (days): {min_val_log}")
print(f"Max target (days): {max_val_log}")

Min target (days): 0.0
Max target (days): 2.8073549270629883

In [59]:
df_train.sample(10)

,timestamp,test_type,test_value,patient_id,label,start_date,end_date,machine_year_full,delta_time_seconds,time_from_start_seconds,patient_span_days,hour_of_day,hour_of_day_scaled,countdown_days_target,countdown_days_log_target,countdown_days_target_scaled,countdown_days_log_target_scaled
15424233,2023-10-31 09:31:46.800,flow,15.70,27,0,2023-10-30 08:24:36.000,2023-11-06 08:24:35,Y2A17601035_2023_good,0.0,90430.8,6.999988,9,0.375000,5,2.584962,0.833333,0.920782
52175194,2022-12-10 02:21:17.400,flow,3.30,67,1,2022-12-04 23:25:17.000,2022-12-11 23:25:16,Y2A21104526_2023_bad,0.0,442560.4,6.999988,2,0.083333,1,1.000000,0.166667,0.356207
69231042,2024-01-25 13:49:39.400,pressure,4.59,84,1,2024-01-22 09:13:50.200,2024-01-28 20:07:57,YSD21503317_2024_bad,0.0,275749.2,6.454245,13,0.541667,3,2.000000,0.500000,0.712414
20231395,2024-12-24 19:37:44.800,pressure,5.27,35,0,2024-12-24 08:15:17.000,2024-12-31 08:15:16,Y2A21607360_2025_good,0.2,40947.8,6.999988,19,0.791667,6,2.807355,1.000000,1.000000
48943382,2023-05-19 01:08:34.400,flow,12.20,64,1,2023-05-12 18:50:31.200,2023-05-19 08:10:56,Y2A20703184_2023_bad,0.0,541083.2,6.555843,1,0.041667,0,0.000000,0.000000,0.000000
54289125,2023-03-28 01:35:31.200,flow,9.00,70,1,2023-03-26 21:08:30.200,2023-04-02 08:22:29,Y2A21B01199_2023_bad,0.0,102421.0,6.468042,1,0.041667,5,2.584962,0.833333,0.920782
38286783,2021-10-05 10:47:46.800,flow,36.70,58,1,2021-10-04 10:37:17.200,2021-10-11 10:04:14,B3320402093_2023_bad,0.2,87029.6,6.977046,10,0.416667,5,2.584962,0.833333,0.920782
36687627,2023-10-31 21:16:11.000,pressure,5.50,57,0,2023-10-30 20:00:48.200,2023-11-06 03:26:48,YSE23104366_2023_good,0.0,90922.8,6.309720,21,0.875000,5,2.584962,0.833333,0.920782
26919554,2024-12-26 09:56:33.400,pressure,6.00,45,0,2024-12-24 12:53:10.200,2024-12-31 12:51:12,Y2C21A01536_2025_good,0.2,162203.2,6.998632,9,0.375000,5,2.584962,0.833333,0.920782
53500081,2021-10-06 22:54:06.000,pressure,3.87,68,1,2021-10-04 19:42:53.200,2021-10-07 11:12:22,Y2A21106018_2023_bad,0.2,184272.8,2.645472,22,0.916667,0,0.000000,0.000000,0.000000

(2) scaling for  test_value (x)

In [60]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np

TYPES = ["pressure", "flow"]
SCALED_COL = "test_value_scaled"

# init output column
for df in (df_train, df_val, df_test):
    df[SCALED_COL] = np.nan

scalers = {}

for t in TYPES:
    # ---- Fit on TRAIN only for this type ----
    m_train = (df_train["test_type"] == t) & df_train["test_value"].notna()
    if not m_train.any():
        # no data of this type in train -> skip this type
        continue

    x_train = df_train.loc[m_train, ["test_value"]].astype("float64")

    # handle zero-variance edge case
    if x_train["test_value"].min() == x_train["test_value"].max():
        scalers[t] = None  # mark as constant; we’ll assign 0.0 later
    else:
        scaler = MinMaxScaler()
        scaler.fit(x_train)
        scalers[t] = scaler

    # ---- Transform each split for this type ----
    for df in (df_train, df_val, df_test):
        m = (df["test_type"] == t) & df["test_value"].notna()
        if not m.any():
            continue

        if scalers[t] is None:
            # constant feature in train -> map to 0.0
            df.loc[m, SCALED_COL] = 0.0
        else:
            vals = df.loc[m, ["test_value"]].astype("float64")
            df.loc[m, SCALED_COL] = scalers[t].transform(vals)
            # optional safety if val/test exceed train min-max
            df.loc[m, SCALED_COL] = df.loc[m, SCALED_COL].clip(0.0, 1.0)

# quick checks
print(df_train[[ "test_type", "test_value", "test_value_scaled"]].head())
print(df_val  [[ "test_type", "test_value", "test_value_scaled"]].head())
print(df_test [[ "test_type", "test_value", "test_value_scaled"]].head())

  test_type  test_value  test_value_scaled
0  pressure        5.37           0.027914
1      flow       77.70           0.486997
2      flow      -37.80           0.002517
3  pressure        4.04           0.021000
4  pressure        3.78           0.019649
  test_type  test_value  test_value_scaled
0  pressure        4.04           0.021000
1      flow       15.70           0.226930
2  pressure        4.09           0.021260
3      flow       16.40           0.229866
4      flow       16.50           0.230285
  test_type  test_value  test_value_scaled
0  pressure        3.91           0.020324
1      flow       67.00           0.442114
2      flow       69.10           0.450923
3  pressure        3.96           0.020584
4  pressure        4.39           0.022819

In [61]:
# Assuming you stored them in a dict called scalers = {"pressure": ..., "flow": ...}

for t, scaler in scalers.items():
    if scaler is None:  # handle constant-value case
        print(f"{t}: constant feature in train (min = max)")
        continue
    min_val = scaler.data_min_[0]
    max_val = scaler.data_max_[0]
    print(f"{t} → min={min_val:.4f}, max={max_val:.4f}")

pressure → min=0.0000, max=192.3800
flow → min=-38.4000, max=200.0000

In [62]:
df_train.sample(10)

,timestamp,test_type,test_value,patient_id,label,start_date,end_date,machine_year_full,delta_time_seconds,time_from_start_seconds,patient_span_days,hour_of_day,hour_of_day_scaled,countdown_days_target,countdown_days_log_target,countdown_days_target_scaled,countdown_days_log_target_scaled,test_value_scaled
15593650,2023-11-01 05:35:51.600,flow,55.40,27,0,2023-10-30 08:24:36.000,2023-11-06 08:24:35,Y2A17601035_2023_good,0.0,162675.6,6.999988,5,0.208333,5,2.584962,0.833333,0.920782,0.393456
12039094,2024-12-27 18:45:52.400,flow,56.90,15,0,2024-12-24 09:50:23.200,2024-12-31 09:50:03,B3C24513203_2025_good,0.0,291329.2,6.999766,18,0.750000,3,2.000000,0.500000,0.712414,0.399748
5668419,2024-12-28 00:38:05.000,flow,8.20,7,0,2024-12-24 13:06:55.200,2024-12-31 13:05:48,B3C23619117_2025_good,0.2,300669.8,6.999222,0,0.000000,3,2.000000,0.500000,0.712414,0.195470
16605881,2023-11-05 08:57:01.800,flow,12.20,27,0,2023-10-30 08:24:36.000,2023-11-06 08:24:35,Y2A17601035_2023_good,0.0,520345.8,6.999988,8,0.333333,0,0.000000,0.000000,0.000000,0.212248
50923413,2022-12-06 01:37:38.400,flow,32.70,67,1,2022-12-04 23:25:17.000,2022-12-11 23:25:16,Y2A21104526_2023_bad,0.2,94341.4,6.999988,1,0.041667,5,2.584962,0.833333,0.920782,0.298238
24530311,2023-06-05 16:24:59.800,flow,23.00,44,0,2023-06-03 12:00:00.000,2023-06-10 11:59:59,Y2C21604310_2023_good,0.0,188699.8,6.999988,16,0.666667,4,2.321928,0.666667,0.827087,0.257550
59968022,2024-04-20 19:31:23.600,pressure,10.20,76,1,2024-04-17 17:42:36.000,2024-04-24 17:42:35,Y2C19408118_2024_bad,0.0,265727.6,6.999988,19,0.791667,3,2.000000,0.500000,0.712414,0.053020
62112645,2021-04-13 00:25:47.000,flow,7.00,79,1,2021-04-07 00:10:40.000,2021-04-14 00:10:39,Y2D20215150_2023_bad,0.2,519307.0,6.999988,0,0.000000,0,0.000000,0.000000,0.000000,0.190436
5385883,2024-12-26 22:10:09.000,pressure,3.78,7,0,2024-12-24 13:06:55.200,2024-12-31 13:05:48,B3C23619117_2025_good,0.2,205393.8,6.999222,22,0.916667,4,2.321928,0.666667,0.827087,0.019649
7502166,2024-12-28 07:54:56.600,flow,26.70,8,0,2024-12-24 22:40:42.000,2024-12-31 22:40:41,B3C23C24308_2025_good,0.2,292454.6,6.999988,7,0.291667,3,2.000000,0.500000,0.712414,0.273070

(3) scaling for  time_from_start_seconds (x)

In [63]:
from sklearn.preprocessing import MinMaxScaler

# Fit on train only
time_from_start_scaler = MinMaxScaler()
time_from_start_scaler.fit(df_train[['time_from_start_seconds']])

# Transform all splits
df_train['time_from_start_scaled'] = time_from_start_scaler.transform(df_train[['time_from_start_seconds']])
df_val['time_from_start_scaled']   = time_from_start_scaler.transform(df_val[['time_from_start_seconds']])
df_test['time_from_start_scaled']  = time_from_start_scaler.transform(df_test[['time_from_start_seconds']])

In [64]:
print("Scaler fitted on time_from_start_seconds from df_train:")
print("Min value:", time_from_start_scaler.data_min_[0])
print("Max value:", time_from_start_scaler.data_max_[0], f"{time_from_start_scaler.data_max_[0]/(3600*24):.2f}","days")

Scaler fitted on time_from_start_seconds from df_train:
Min value: 0.0
Max value: 604799.0 7.00 days

In [65]:
# Add collection tag to each split (fastest)
df_train.loc[:, 'collection'] = 'train'
df_val.loc[:,   'collection'] = 'val'
df_test.loc[:,  'collection'] = 'test'

In [66]:
df_train.head(5)

,timestamp,test_type,test_value,patient_id,label,start_date,end_date,machine_year_full,delta_time_seconds,time_from_start_seconds,patient_span_days,hour_of_day,hour_of_day_scaled,countdown_days_target,countdown_days_log_target,countdown_days_target_scaled,countdown_days_log_target_scaled,test_value_scaled,time_from_start_scaled,collection
0,2023-10-25 13:04:44.200,pressure,5.37,2,0,2023-10-25 13:04:44.200,2023-10-31 22:17:08,B3A20605023_2023_good,0.0,0.0,6.383609,13,0.541667,6,2.807355,1.0,1.0,0.027914,0.000000e+00,train
1,2023-10-25 13:04:44.200,flow,77.70,2,0,2023-10-25 13:04:44.200,2023-10-31 22:17:08,B3A20605023_2023_good,0.0,0.0,6.383609,13,0.541667,6,2.807355,1.0,1.0,0.486997,0.000000e+00,train
2,2023-10-25 13:04:44.400,flow,-37.80,2,0,2023-10-25 13:04:44.200,2023-10-31 22:17:08,B3A20605023_2023_good,0.2,0.2,6.383609,13,0.541667,6,2.807355,1.0,1.0,0.002517,3.306884e-07,train
3,2023-10-25 13:04:44.400,pressure,4.04,2,0,2023-10-25 13:04:44.200,2023-10-31 22:17:08,B3A20605023_2023_good,0.0,0.2,6.383609,13,0.541667,6,2.807355,1.0,1.0,0.021000,3.306884e-07,train
4,2023-10-25 13:04:44.600,pressure,3.78,2,0,2023-10-25 13:04:44.200,2023-10-31 22:17:08,B3A20605023_2023_good,0.2,0.4,6.383609,13,0.541667,6,2.807355,1.0,1.0,0.019649,6.613768e-07,train

# save the dfs

In [67]:
import os
import pandas as pd

# Where to save
ROOT = r"D:\Medical_AI\Cleaned\7days_rawdata_parquet"

# Ensure folder
os.makedirs(ROOT, exist_ok=True)

def _prep_for_parquet(df: pd.DataFrame) -> pd.DataFrame:
    """Optional: light prep for smaller/faster parquet files."""
    d = df.copy(deep=False)
    # Make sure timestamps are datetime
    if 'timestamp' in d.columns:
        d['timestamp'] = pd.to_datetime(d['timestamp'], errors='coerce')
    # Strings with few unique values compress better as category
    for col in ('test_type', 'machine_year_full', 'collection'):
        if col in d.columns and d[col].dtype == object:
            d[col] = d[col].astype('category')
    return d

# ---- Save (single parquet per split) ----
df_train.to_parquet(os.path.join(ROOT, "train.parquet"), engine="pyarrow", index=False)
df_val.to_parquet(  os.path.join(ROOT, "val.parquet"),   engine="pyarrow", index=False)
df_test.to_parquet( os.path.join(ROOT, "test.parquet"),  engine="pyarrow", index=False)